### ISSUE TITLE
Update plugin if it already installed

### ISSUE THREAD

**Issue by php-coder** [jenkinsci/puppet-jenkins#11]
Jenkins 1.509.2 provided bundled javadoc plugin with version 1.0

When I want to update it to the latest version (or manually specify it):

```
class { 'jenkins':                                                                                  
  lts => 1
  repo => 1
  plugin_hash => {                                                                                  
    'javadoc' => { version => '1.1' }
  }
}
```
Plugin wasn't updated because code only checks if plugin presents or not. It would be better to also check installed version and update plugin if newer version requested.

**Comment by jhoblitt** [comment]
This has been complimented for some time (several years it looks like).
