### ISSUE TITLE
"invalid option: -p" for Jenkins Slave Status in CentOS 6.5

### ISSUE THREAD

**Issue by krische** [jenkinsci/puppet-jenkins#133]
I'm using the `jenkins::slave` class to create a Jenkins slave in CentOS 6.5 (minimal version). It looks like the init.d script for the service isn't behaving correctly. In the `slave_status()` function it calls `status -p $PID_FILE` and it looks like "-p" isn't a valid parameter for the status program, so it throws an error.

**Comment by jhoblitt** [comment]
This appears to have been fixed in #171.
