### ISSUE TITLE
support for disabling plugins

### ISSUE THREAD

**Issue by eops-wedgwood** [jenkinsci/puppet-jenkins#136]
I'd love to see support for disabling Jenkins plugins. The core distribution ships with some plugins that aren't necessarily used in all deployments (i.e. CVS). This can be handled by writing an empty "{plugin-name}.jpi.disabled" file to the plugins directory.

**Comment by jhoblitt** [comment]
#209 resolves this issue.  It can be closed.

**Comment by gregswift** [comment]
@jhoblitt I'm sitting here researching the plugin behaviors and when i read #209 i got confused because I do not see how that credentials fix resolves this plugins issue? I didnt notice anything in that explaining it.  Could you clarify?

**Comment by jhoblitt** [comment]
@gregswift My apologies, it was the PR merged after that, #212   That PR was released as part of `v1.4.0`.  I'm going to close this issue but please feel free to reopen it if there is a bug with this functionality.
