### ISSUE TITLE
Credentials class appears to keep recreating user

### ISSUE THREAD

**Issue by sharkannon** [jenkinsci/puppet-jenkins#193]
I'm using the new jenkins::credentials feature to create a user in our managed jenkins instance, but it appears that each time puppet is run, the user is either recreated the user instead of updating it (Basically we have to select the user again in the SVN plugin for each project).
 (Note, private information has been changed, such as the username and password)
Class call:
```
jenkins::credentials {'USERNAME':
    password            => 'PASSWORD',
}
```
The following is output each time puppet is run:
```
/Stage[main]/Buildserver/Jenkins::Credentials[username]/Exec[create-jenkins-credentials-USERNAME]/returns: executed successfully
```
Jenkins Version: 1.565.2 (LTS)
Credentials Version: 1.16.1

**Comment by rtyler** [comment]
ETIMEOUT, I'm just going to roll this into the 1.4.0 release
