### ISSUE TITLE
$PATH inside of exec definitions

### ISSUE THREAD

**Issue by slauger** [jenkinsci/puppet-jenkins#211]
I've got the following error using your module.

Error: Failed to apply catalog: Validation of Exec[reload-jenkins] failed: 'java -jar /usr/share/jenkins/jenkins-cli.jar -s http://localhost:8080 reload-configuration' is not qualified and no path was specified. Please qualify the command or specify a path. at /etc/puppet/modules/jenkins/manifests/cli.pp:41
Wrapped exception:
'java -jar /usr/share/jenkins/jenkins-cli.jar -s http://localhost:8080 reload-configuration' is not qualified and no path was specified. Please qualify the command or specify a path.

I needed to patch cli.pp manually and changed the line

  # The jenkins cli command with required parameter(s)
  $cmd = "java -jar ${jar} -s http://localhost:${port}"

to

  # The jenkins cli command with required parameter(s)
  $cmd = "/usr/bin/java -jar ${jar} -s http://localhost:${port}"

Please use the complete path to the command(s) or set the "path" argument.

**Comment by TJM** [comment]
I just got bit by this, when will this be "released" ?

~tommy

**Comment by dsbaars** [comment]
+1 also got hit
