### ISSUE TITLE
problem with configuring jenkins:config_hash

### ISSUE THREAD

**Issue by michalbagrowski** [jenkinsci/puppet-jenkins#221]
HI

I need to configure slaveAgentPort, i use such code for installing jenkins with plugins:

```

include jenkins

$plugins = [
  'swarm'
]

jenkins::plugin { $plugins:
}
```

but i ca not figure out what should be syntax to use config_hash

```
$config_hash = {
        'slaveAgentPort' => { 'value' =>  22222}
}

jenkins::config {$config_hash}

```
^this of course is not work

````
Error: Could not parse for environment production: Syntax error at '}' at /etc/puppet/manifests/site.pp:15 on node ip-10-5-148-210.ec2.internal
Error: Could not parse for environment production: Syntax error at '}' at /etc/puppet/manifests/site.pp:15 on node ip-10-5-148-210.ec2.internal
```

can anybody suggest how to fix this?

**Comment by dp80** [comment]
This worked for me from hiera common.yaml
`
jenkins::params::config_hash        		: { JENKINS_PORT: { value : '8090' }, JENKINS_HOME : { value : '/opt/mount2/jenkins' } } `

**Comment by jhoblitt** [comment]
Hi @michalbagrowski - I'm going to close out this issue.  Please feel free to reopen it if you can reproduce the problem with the current release.
