### ISSUE TITLE
Jenkins security setting is lost after service restart

### ISSUE THREAD

**Issue by iax7** [jenkinsci/puppet-jenkins#223]
I have configured my jenkins instance in ubuntu 12.04 using

```puppet
  class { '::jenkins::security':
    security_model => 'full_control',
  }
```

which sets the settings to use user/password correctly, but  if I restart the service these settings are lost, giving the world full access without user/password...

Is this by design?

**Comment by Xylakant** [comment]
restarting sets the security back to what's in your config.xml. It seems to me that jenkins does not correctly persist the setting. Seems like a jenkins bug to me.

**Comment by jhoblitt** [comment]
@iax7 / @Xylakant Could either of you try to reproduce this issue with the current master and reopen this issue if it is still present?
