### ISSUE TITLE
Support for setting UUID of user during credentials creation

### ISSUE THREAD

**Issue by madAndroid** [jenkinsci/puppet-jenkins#226]
When I create a job using `jenkins::job`, with a specified UUID in the template, I'd like to be able to set that UUID during credential creation.

**Comment by ltutar** [comment]
For my own understanding.
Do you mean the 'id' line as shown below? I can set this value through Jenkins GUI but not through puppet? and breaks my automated jenkins provisioning.

    <java.util.concurrent.CopyOnWriteArrayList>
        <com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl>
          <scope>GLOBAL</scope>
          <id>dbd9a6c8-c7c5-428b-946e-9c3e2333ef58</id>
          <description>vagrant user for git</description>
          <username>vagrant</username>
          <password>w5oFlgURdduq2RlLJQBJUTmOEeJvFdC4geAHiW3K0Hk=</password>
        </com.cloudbees.plugins.credentials.impl.UsernamePasswordCredentialsImpl>
      </java.util.concurrent.CopyOnWriteArrayList>

**Comment by madAndroid** [comment]
@ltutar - yes indeed  ... it's used in numerous places, for example:
http://docs.openstack.org/infra/jenkins-job-builder/scm.html#scm.git refers to it as 'credentials-id', which allows you to set it for use with JJB

I also use it in the job-dsl when specifying credentials to use when needed
