### ISSUE TITLE
Master 1.3.0 inconsistent with forge 1.3.0 tarball

### ISSUE THREAD

**Issue by endyman** [jenkinsci/puppet-jenkins#232]
The path fix in cli.pp (https://github.com/jenkinsci/puppet-jenkins/commit/fcd61537a39405d7f9cbbcd2ab3d82facab934dc#diff-51306f26e2f26dcf062139b157b7f3ff) and the credentials retry fix are not included in the forge 1.3.0 tarball although the metadata.json at both places (git and forge) state version 1.3.0.
Please implement proper versioning and update the forge module.

**Comment by rtyler** [comment]
Master is the development branch which contains that fix, and is going to be in the 1.4..0 release of the module. The version 1.3.0 on Forge matches the v1.3.0 tag of this repository
