### ISSUE TITLE
conditional-buildstep and run-condition jenkins plugins do not get installed through Puppet script

### ISSUE THREAD

**Issue by profanand** [jenkinsci/puppet-jenkins#240]
I have written a Puppet script that will install conditional-build and run-condition jenkins plugin. But the plugins do not get installed through the Puppet script. 
     The plugins DO get installed manually through the jenkins web interface. The manual installation installs .jpi files in the var/lib/jenkins/plugins folder. I tried to remove the .jpi files manually and then do a "Vagrant provision" after which the plugins get installed. This is a very strange behaviour as previously no matter how many times I tried to do a "Vagrant destroy" and "Vagrant reload" and "Vagrant provision"..the plugins never got installed but as soon as I installed the plugins through the jenkins web interface, and then removed the .jpi files from the puppet VM, and then did a "Vagrant provision"..VIOLA the plugins get installed through the puppet script.
        At first I thought that the plugins weren't getting installed thorough the puppet script because the puppet script downloads a .hpi file and a conditional-build/run-condition folder instead of a .jpi file which the jenkins web interface downloads in the /var/lib/jenkins/plugins folder. But I was mistaken as jenkins accepts even the .hpi files after I remove the .jpi file and then do a "Vagrant provision" which then downloads the .hpi file and a plugin-named folder in the jenkins/plugins folder. I wonder if this is a bug because I didn't find a solution for this.

Below is the puppet script:-
service { iptables: ensure => stopped }

class {'jenkins':
}

jenkins::plugin { "git" :
version => '1.1.28',
} ->

jenkins::plugin { 'github':
version => '0.7',
} ->

jenkins::plugin { 'run-condition':
version => '1.0',
} ->

jenkins::plugin { 'conditional-buildstep':
version => '1.3.3',
}

**Comment by profanand** [comment]
service { iptables: ensure => stopped }

class {'jenkins':
}

jenkins::plugin { "git" :
  version => '1.1.28',
} ->

jenkins::plugin { 'github':
  version => '0.7',
} ->

jenkins::plugin { 'run-condition':
  version => '1.0',
} ->

jenkins::plugin { 'conditional-buildstep':
 version => '1.3.3',
}

**Comment by rtyler** [comment]
There are problably dependencies missing for those plugins that are not enumerated in the within the Puppet code.

Currently puppet-jenkins cannot do plugin dependency resolution for you

**Comment by profanand** [comment]
I doubt if there are any more dependencies because conditional-buildstep needs run-condition which is already present...and as I described the scenario that the plugins do get installed but only after I remove the .jpi files manually(Jenkins interface installation files) and then run the puppet script(vagrant provision)..If anyone can try installing these plugins through my code and tweak with it if possible, that would be great..this way we can confirm if this is really a bug..thanks.

**Comment by tykeal** [comment]
@profanand 

Per https://wiki.jenkins-ci.org/display/JENKINS/Conditional+BuildStep+Plugin the following modules are also required:

maven-plugin (v1.480.3)  [this one is bundled with jenkins though not always the latest version]

run-condition (v1.0) [which you are installing]

token-macro (v1.5.1) [you aren't installing this that I can see in your manifest snippet] <--- this is likely your problem.
