### ISSUE TITLE
keeping jenkins version current with lts

### ISSUE THREAD

**Issue by mmarseglia** [jenkinsci/puppet-jenkins#243]
I've installed jenkins using the puppet module and specified lts.  The current lts version is 1.580.3 but our jenkins is still at 1.579.  Will the puppet module update jenkins to the most current lts version or are upgrades done manually?

` class { 'jenkins':
    lts                => true,
    configure_firewall => false,
    plugin_hash        => $plugin_hash,
  }`

**Comment by rtyler** [comment]
Right now, the puppet module will not upgrade Jenkins for you.
