### ISSUE TITLE
Could not find declared class java 

### ISSUE THREAD

**Issue by Chenyfg** [jenkinsci/puppet-jenkins#247]
Hi All.
I downloaded puppet-jenkins into my puppet modules folder "/etc/puppet/modules/jenkins/", when I run "puppet agent -t" on the puppet client, I got below error:

err: Could not retrieve catalog from remote server: Error 400 on SERVER: Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class java at /etc/puppet/modules/jenkins/manifests/init.pp:136 

Could you please kindly help to point out what's the issue is?

Thanks very much for your help.

**Comment by matthewbarr** [comment]
Can you post how you called it in your manifest?(site.pp, etc?)

**Comment by matthewbarr** [comment]
It's looking for a module called Java, which would normally be installed as a dependency..

**Comment by Chenyfg** [comment]
Please refer to below content in /etc/puppet/modules/jenkins/manifests/init.pp:(this file is the same as the one in github)

class jenkins(
  $version            = $jenkins::params::version,
  $lts                = $jenkins::params::lts,
  $repo               = $jenkins::params::repo,
  $service_enable     = $jenkins::params::service_enable,
  $service_ensure     = $jenkins::params::service_ensure,
  $config_hash        = {},
  $plugin_hash        = {},
  $job_hash           = {},
  $configure_firewall = undef,
  $install_java       = $jenkins::params::install_java,
  $proxy_host         = undef,
  $proxy_port         = undef,
  $no_proxy_list      = undef,
  $cli                = undef,
  $port               = $jenkins::params::port,
  $libdir             = $jenkins::params::libdir,
) inherits jenkins::params {

  validate_bool($lts, $install_java, $repo)
  validate_hash($config_hash, $plugin_hash)

  if $configure_firewall {
    validate_bool($configure_firewall)
  }

  if $no_proxy_list {
    validate_array($no_proxy_list)
  }

  anchor {'jenkins::begin':}
  anchor {'jenkins::end':}

  if $install_java {
    class {'java':
      distribution => 'jdk'
    }
  }

  if $repo {
    include jenkins::repo
  } 
  .......
I copied the entire module from github and did not do any change. It have JAVA installed in the Linux server:
java version "1.4.2"
gij (GNU libgcj) version 4.1.2 20080704 (Red Hat 4.1.2-52)

You mean I need to create a module called Java under jenkins/manifests folder:

-rw-rw-r-- 1 root root  806 Oct 27 04:07 cli_helper.pp
-rw-rw-r-- 1 root root 1357 Oct 27 04:07 cli.pp
-rw-rw-r-- 1 root root  566 Oct 27 04:07 config.pp
-rw-rw-r-- 1 root root 1757 Oct 27 04:07 credentials.pp
-rw-rw-r-- 1 root root  421 Oct 27 04:07 firewall.pp
-rw-rw-r-- 1 root root 5401 Feb 10 17:03 init.pp
drwxrwxr-x 2 root root 4096 Oct 27 04:07 job
-rw-rw-r-- 1 root root  707 Oct 27 04:07 job.pp
-rw-rw-r-- 1 root root  221 Oct 27 04:07 jobs.pp
-rw-rw-r-- 1 root root  188 Oct 27 04:07 master.pp
-rw-rw-r-- 1 root root  403 Oct 27 04:07 package.pp
-rw-rw-r-- 1 root root  575 Oct 27 04:07 params.pp
-rw-rw-r-- 1 root root 3765 Oct 27 04:07 plugin.pp
-rw-rw-r-- 1 root root  231 Oct 27 04:07 plugins.pp
-rw-rw-r-- 1 root root  496 Oct 27 04:07 proxy.pp
drwxrwxr-x 2 root root 4096 Oct 27 04:07 repo
-rw-rw-r-- 1 root root 1026 Oct 27 04:07 repo.pp
-rw-rw-r-- 1 root root  995 Oct 27 04:07 security.pp
-rw-rw-r-- 1 root root  335 Oct 27 04:07 service.pp
-rw-rw-r-- 1 root root 5326 Oct 27 04:07 slave.pp
-rw-rw-r-- 1 root root  453 Oct 27 04:07 sysconfig.pp
-rw-rw-r-- 1 root root 1766 Oct 27 04:07 user.pp
[root@XXX manifests]# pwd
/etc/puppet/modules/jenkins/manifests
[root@XXX manifests]#

**Comment by matthewbarr** [comment]
You may want to install via the module tool, which would install the puppet labs Java module. That's what it's looking for.

**Comment by Chenyfg** [comment]
I will try, thx for your help.

**Comment by Chenyfg** [comment]
Thx matthewbarr. I installed the puppetlabs Java module, but I encounted below error:

err: /Stage[main]/Jenkins::Package/Package[jenkins]/ensure: change from absent to present failed: Execution of '/usr/bin/yum -d 0 -e 0 -y install jenkins' returned 1: Error: Cannot retrieve repository metadata (repomd.xml) for repository: jenkins. Please verify its path and try again

This is because my Linux server can not connect to internet, can I download and install Jenkins manually and manage Jenkins with Puppet like Jenkins plugins?

**Comment by Chenyfg** [comment]
BTW, did puppet-jenkins support Windows?

**Comment by Chenyfg** [comment]
Hi, actually my requirement is that: I need a puppet server to help me to install Java/Ant/Jenkins, and install Jenkins plugins on many Windows machine. I wonder to know whether this puppet-jenkins module support my requirement or not. If it can, how can I implement this? Thx

**Comment by matthewbarr** [comment]
Are you sure you need to install plugins on the windows systems? Are they all running Jenkins masters?  You may want to look at slaves. 

Could you please post your node definition?

**Comment by Chenyfg** [comment]
Hi Matthewbarr, we all use Jenkins masters and install plugins on windows systems.

**Comment by Chenyfg** [comment]
Hi Matthewbarr, is there any suggestion?  thx

**Comment by Chenyfg** [comment]
Also the plugins are all locate in Puppet master server.

**Comment by matthewbarr** [comment]
Can you please post your site.pp? Or whatever you use to do node classification?

**Comment by matthewbarr** [comment]
The basic instructions in the readme should be at least a start..

**Comment by Chenyfg** [comment]
Please refer to below:
site.pp:
node default {
import 'nodes.pp'
}

nodes.pp:
node 'XXXXX' {
        include stdlib
        include jenkins
}

**Comment by matthewbarr** [comment]
You probably don't need "include sodlib" in the nodes.pp, but you do need to have both the jenkins module installed & the java module installed on the master.

puppet module install rtyler-jenkins
puppet module install puppetlabs-java

(https://forge.puppetlabs.com/puppetlabs/java)

**Comment by Chenyfg** [comment]
For one more question, did rthler-jenkins support Windows system? As I got "did not support Windows OS". thx

**Comment by matthewbarr** [comment]
Are you trying to install on windows? It doesn't support windows.  We are happy to accept pull requests, even for basic functionailty..

**Comment by Chenyfg** [comment]
Yes, I am trying to use puppet master on Linux to install Jenkins on windows. I wonder to know how to pull requests. My requirement is: install puppet-jenkins module on Linux, and manage Jenkins masters on windows, and support to install Jenkins plugins, which as the same behavior on Linux system. Can you get what I mean?

**Comment by matthewbarr** [comment]
I don't believe we support installing jenkins on windows. Sorry.

You could use a windows slave, but that might not help you.  

We are happy to accept pull requests for windows support, but probably won't be getting it done ourselves too soon :(

**Comment by Chenyfg** [comment]
I see, I will search for another way. Anyway, appreciate for your help.
