### ISSUE TITLE
Jenkins::Slave wget needs proxy configuration

### ISSUE THREAD

**Issue by phathocker** [jenkinsci/puppet-jenkins#248]
<pre>
Notice: /Stage[main]/Java/Package[java]/ensure: created
Notice: /Stage[main]/Jenkins::Slave/User[jenkins-slave_user]/ensure: created
Error: Command exceeded timeout
Wrapped exception:
execution expired
Error: /Stage[main]/Jenkins::Slave/Exec[get_swarm_client]/returns: change from notrun to 0 failed: Command exceeded timeout
</pre>

**Comment by andrewegel** [comment]
I too would like this feature - However @phathocker I have this work around - I set 

```
  Exec {
    environment => [
      "http_proxy=<your-proxy-config>",
      "HTTP_PROXY=<your-proxy-config>",
    ]
  }
```

Before I make any calls to 

```class { "jenkins::slave": }```

I realize this isn't ideal, but thought id share my work-around.

**Comment by phathocker** [comment]
@andrewegel - Thanks for the suggestion.  That is also how I am doing it.

**Comment by jhoblitt** [comment]
Usage of `wget` has been completed removed on current master.
