### ISSUE TITLE
Path to $libdir hardcoded in few manifests

### ISSUE THREAD

**Issue by RobertLask** [jenkinsci/puppet-jenkins#249]
We needed to deploy Jenkins into alternate location on the file system. To achieve this we had to set the custom $config_hash = { 'JENKINS_HOME' => { 'value' => "$jenkins::params::jenkins_home" },
and different value $jenkins::params::libdir. 

However, following modules have a hard coded path to /var/lib/jenkins/. 
/plugin.pp
/package.pp
/proxy.pp
/job/present.pp
/job/absent.pp

Suggesting a change to allow for use of  $jenkins::params::libdir across all modules.

Also the dedicated $jenkins::params::jenkins_home which would not require $config_hash would be nice.

Robert

**Comment by costela** [comment]
We'd also appreciate having this issue solved.
Note however that $libdir is actually "/usr/lib" or "/usr/share", depending on $::osfamily, and is where the actual jenkins.war is located (i.e.: unrelated to the JENKINS_HOME setting). "/var/lib" doesn't currently have a corresponding parameter at all and is actually hard-coded in the jenkins packages from pkg.jenkins-ci.org. The package creates the (empty) directory and includes the default/jenkins file pointing jenkins to it.

To be truer to the puppet-spirit, maybe all variables in the default/jenkins file should be explicitly managed by the module? This would mean the elegant solution of using create_resources() over $config_hash would need to be rethought, but it would free the admin of having to look at the file to see what arguments are supported.

**Comment by jhoblitt** [comment]
The `localstatedir` param introduced in #396, along with internal re-factoring should address this.
