### ISSUE TITLE
cli.pp needs exec path => '/usr/bin....'

### ISSUE THREAD

**Issue by phathocker** [jenkinsci/puppet-jenkins#251]
Getting this error:

<pre>
Error: Failed to apply catalog: Validation of Exec[reload-jenkins] failed: 'java -jar /usr/lib/jenkins/jenkins-cli.jar -s http://localhost:8080 reload-configuration' is not qualified and no path was specified. Please qualify the command or specify a path. at /etc/puppetlabs/puppet/environments/latest/modules/jenkins/manifests/cli.pp:35
Wrapped exception:
'java -jar /usr/lib/jenkins/jenkins-cli.jar -s http://localhost:8080 reload-configuration' is not qualified and no path was specified. Please qualify the command or specify a path.
</pre>

I temporarily change $cmd in cli.pp to this and it worked:

<pre>
$cmd = "/usr/bin/java -jar ${jar} -s http://localhost:${port}"
</pre>

**Comment by iax7** [comment]
This is already fixed. Instread of installing the module from puppet forge that is now somewhat outdated, try cloning the proyect from github.

**Comment by phathocker** [comment]
@iax7 Does that mean it is time for a new release?

**Comment by iax7** [comment]
I think so

**Comment by iMelnik** [comment]
It's really time for a new release

**Comment by phathocker** [comment]
:+1:

**Comment by jpinsonault** [comment]
:+1: A new release with that fix would be great

**Comment by iax7** [comment]
It's taking so long!

**Comment by phathocker** [comment]
@rtyler Can you help?

**Comment by rtyler** [comment]
1.4.0 is out
