### ISSUE TITLE
using jenkins::job with jenkins::cli_helper ends up in dependency loop

### ISSUE THREAD

**Issue by Xylakant** [jenkinsci/puppet-jenkins#258]
If security is enabled on a jenkins system and an ssh key must be specified in jenkins::cli_helper it's impossible to avoid a dependency loop since Jenkins::Job::Present depends on Exec['restart-jenkins']:

The dependency  Class["::jenkins::cli_helper"] -> Jenkins::Job <| |> (or similar) must be specified since otherwise the cli does not use the SSH key and thus fails. If the dependency is specified, puppet ends up in this loop:

(Exec[jenkins update-job testjob] => Exec[reload-jenkins] => Class[Jenkins::Cli] => File[/var/opt/jenkins/puppet_helper.groovy] => Class[Jenkins::Cli_helper] => Jenkins::Job[testjob] => Jenkins::Job::Present[testjob] => Exec[jenkins update-job testjob])

![recource cycle](https://cloud.githubusercontent.com/assets/337823/6804600/e0fa78d2-d23e-11e4-8ed6-2d6d5c38b224.png)

I don't see an easy way out other than refactoring jenkins::cli_helper.

**Comment by Xylakant** [comment]
on a second look, removing https://github.com/jenkinsci/puppet-jenkins/blob/master/manifests/cli_helper.pp#L21 seems to fix the issue with no adverse effects.

**Comment by jhoblitt** [comment]
Is this resolved by https://github.com/jenkinsci/puppet-jenkins/pull/260 ?

**Comment by jhoblitt** [comment]
I am assuming this has long since been resolved.
