### ISSUE TITLE
Missleading documentation regarding HTTP_PORT

### ISSUE THREAD

**Issue by mitfik** [jenkinsci/puppet-jenkins#263]
Hi,

Could anyone explain what is the different between HTTP_PORT and JENKINS_PORT?

In many places in the code (jenkins_port function, jenkins::config etc) and tests you are using HTTP_PORT, but of course if you will pass through HTTP_PORT to config_hash you will not change the port on which jenkins is running. For that you have to set JENKINS_PORT instead. But in some parts of the documentation you mentioning about HTTP_PORT. It seems that someone forgot to update documentation and HTTP_PORT is not valid any more, is that correct?

So to set a port for jenkins you have to:

     class { 'jenkins':
       config_hash => {
         'JENKINS_PORT' => { 'value' => '9090' }
       }
     }

UPDATE:
since in the code there is few references to HTTP_PORT to make it work actually there is a need to set also HTTP_PORT so the proper config should be:

     class { 'jenkins':
       config_hash => {
         'JENKINS_PORT' => { 'value' => '9090' },
         'HTTP_PORT' => { 'value' => '9090' },
       }
     }

If someone could clarify what is the difference between HTTP_PORT and JENKINS port and if my thinking is correct, then I could provide PR with needed changes.

Thanks a lot

**Comment by jhoblitt** [comment]
`HTTP_PORT` is the correct hash key value.  I'm not sure if this was different historically.  I'm going to close this ticket out since there are other tickets (eg., #214) that cover known problems with port configuration.
