### ISSUE TITLE
Broken link on puppetlabs.com page

### ISSUE THREAD

**Issue by mitfik** [jenkinsci/puppet-jenkins#264]
Could not find any place on puppetlabs to report that but on your [page](https://forge.puppetlabs.com/rtyler/jenkins/), the `Project URL` seems to be broken as it is pointing to something like that:

https://forge.puppetlabs.com/rtyler/jenkins/(https://forge.puppetlabs.com/rtyler/puppet-jenkins)

Will be good to have there a link to github page.

Best regards

**Comment by rtyler** [comment]
This is fixed in HEAD right now, but requires another release.
