### ISSUE TITLE
Core plugins not updated at first install

### ISSUE THREAD

**Issue by rmestrum** [jenkinsci/puppet-jenkins#286]
Hi,

I'm using the 1.4.0 release of this module.

I'm using the plugin code like this:
	include jenkins

The yaml file i've put the list of plugins as followed:
	jenkins::plugin_hash:
	  credentials:
	    version:      '1.22'

I'm finding that only core plugins do not update

When puppet runs, it says it installed the plugin:

Notice: /Stage[main]/Jenkins::Package/Package[jenkins]/ensure: created
Notice: /Stage[main]/Jenkins::Plugins/Jenkins::Plugin[credentials]/File[/var/lib/jenkins/plugins]/ensure: created
Notice: /Stage[main]/Jenkins::Plugins/Jenkins::Plugin[credentials]/Exec[download-credentials]/returns: executed successfully
Notice: /Stage[main]/Jenkins::Plugins/Jenkins::Plugin[credentials]/File[/var/lib/jenkins/plugins/credentials.hpi]/owner: owner changed 'root' to 'jenkins'
Notice: /File[/var/lib/jenkins/plugins/credentials.hpi]/seluser: seluser changed 'unconfined_u' to 'system_u'
Info: /Stage[main]/Jenkins::Plugins/Jenkins::Plugin[credentials]/File[/var/lib/jenkins/plugins/credentials.hpi]: Scheduling refresh of Service[jenkins]
Info: /Stage[main]/Jenkins::Plugins/Jenkins::Plugin[credentials]/File[/var/lib/jenkins/plugins/credentials.hpi]: Scheduling refresh of Service[jenkins]
Info: Class[Jenkins::Plugins]: Scheduling refresh of Class[Jenkins::Service]
Info: Class[Jenkins::Service]: Scheduling refresh of Service[jenkins]

I've done some research and i discovered that jenkins creates the *.jpi files on startup. In the puppet class jenkins the jenkins service is started after the plugins are installed.

So when the plugins are installed no *.jpi files for the core packages are available and that means that no .jpi.pinned files are created by the following code when a plugin is installed
	# create a pinned file if the plugin has a .jpi extension
    	#   to override the builtin module versions
	    exec { "create-pinnedfile-${name}" :
	      command => "touch ${plugin_dir}/${name}.jpi.pinned",
	      cwd     => $plugin_dir,
	      require => File[$plugin_dir],
	      path    => ['/usr/bin', '/usr/sbin', '/bin'],
	      onlyif  => "test -f ${plugin_dir}/${name}.jpi -a ! -f ${plugin_dir}/${name}.jpi.pinned",
	      before  => Exec["download-${name}"],
	    }

**Comment by jhoblitt** [comment]
I believe that #389 should resolve the pinning issues.  I'm going to close this issue but please reopen it if this is still reproducible with the current master.
