### ISSUE TITLE
Initscripts shouldn't call su/runuser as login shell

### ISSUE THREAD

**Issue by bigon** [jenkinsci/puppet-jenkins#287]
Hello,

The initscripts are calling su/runuser as login shells.

This should be avoided IMVHO as this is creating a PAM session which can call modules like pam_systemd that would create a logind session. That kind of session should only be created by entrypoint applications (login, ssh, gdm,...) and not by daemons

**Comment by bigon** [comment]
Well to be complete, su command should be avoided completely in initscripts, as it could create bugs like https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=717731

**Comment by jhoblitt** [comment]
@bigon I'm going to close this out as this is really an issue with the upstream jenkins packaging for redhat/debian.  The systemd support that was added to this module does not use `runuser`.
