### ISSUE TITLE
Ubuntu 15.04 Vivid Vervet not supported

### ISSUE THREAD

**Issue by RizzoV** [jenkinsci/puppet-jenkins#293]
Hi everybody,
I just installed the latest version of this plugin (1.4.0) and I'm getting an error when trying to run the "puppet agent --test" command in the agent system. Here it is:

Error: Could not retrieve catalog from remote server: Error 400 on SERVER: unsupported release vivid at /etc/puppetlabs/puppet/environments/production/modules/java/manifests/params.pp:49 on node <NODE RUNNING VIVID VERVET>
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

Obviously the machine where I'm getting this error is running Ubuntu 15.04 Vivid Vervet. I added manually 'vervet' in the same "switch section" of 'utopic' in the params.pp file, since it should be the most similiar version. However, I'm still getting minor (I think...) errors, like:

Info: Computing checksum on file /etc/apt/apt.conf.d/15update-stamp
Error: Could not back up /etc/apt/apt.conf.d/15update-stamp: getaddrinfo: Name or service not known
Error: Could not back up /etc/apt/apt.conf.d/15update-stamp: getaddrinfo: Name or service not known
Error: /Stage[main]/Apt/File[/etc/apt/apt.conf.d/15update-stamp]/content: change from {md5}b9de0ac9e2c9854b1bb213e362dc4e41 to {md5}4355b3e7824866a503fc221621fc65ba failed: Could not back up /etc/apt/apt.conf.d/15update-stamp: getaddrinfo: Name or service not known

Can I make something to avoid this without waiting for an update that will support Vivid Vervet? Thanks in advance.

**Comment by matthewbarr** [comment]
So it looks like you're actually getting an error from the PuppetLabs Java module.  You can manually install java, and disable the java module call.

Hmm. Not actually in the readme.  But it's a parameter to the class, in the init.pp:

# install_java = true (default)
#   - use puppetlabs-java module to install the correct version of a JDK.
#   - Jenkins requires a JRE


So, If you pass a install_java => false,  you'll avoid the bug.  You just have to make sure you have a JRE installed.

However, we should probably also check that the puppet labs java module has this bug open..

**Comment by matthewbarr** [comment]
https://github.com/puppetlabs/puppetlabs-java/blob/master/manifests/params.pp    Has the fix.  I'll ask them to do a release soon, since 15.04 has been out for a bit.

**Comment by RizzoV** [comment]
Wow that was fast! Thanks a lot!!

**Comment by RizzoV** [comment]
I'm still getting the second error, it occours only when the agent server in pinned to the Jenkins group in Puppet. Is there somthing that can I do?

PS: I'm sorry but I'm a newbie both in Jenkins and Puppet!

**Comment by matthewbarr** [comment]
A) if you're going to reopen the issue, you should probably reopen the issue.

B) The problem isn't with our code, unfortunately.  It's a different module- and has to do w/ the version you've downloaded vs the one that's currently being developed.  

I'm not sure what you mean when you say that the agent server is pinned to the Jenkins group in puppet.  
I will note that the updated code for the java module does not fix the problem by adding vivid to the list of releases, but adds a new stanza, because things aren't organized the same for the new OS.  You should be able to download the fix from the other repo:   https://github.com/puppetlabs/puppetlabs-java/blob/master/manifests/params.pp

**Comment by RizzoV** [comment]
I'm sorry about the A), but I didn't even knew I could do it. About the issue, I meant that the error appears only when, from the PE Console, I pin the agent node to the Jenkins group, that is the one where I'm implementing the Jenkins module. That's why I was thinking about a problem with the code. However, now I'm not encoutering that error message anymore.

Thanks again for the support.
