### ISSUE TITLE
need to parameterize $java_version in jenkins/manifests/init.pp 

### ISSUE THREAD

**Issue by hesco** [jenkinsci/puppet-jenkins#308]
```
jenkins:~ # cat /var/log/jenkins.rc
Jenkins requires Java7 or later, but you are running pxa6460sr16fp2-20141026_01 (SR16 FP2) from /usr/lib64/jvm/java-1_6_0-ibm-1.6.0/jre
java.lang.UnsupportedClassVersionError: 50.0
	at Main.main(Main.java:90)
```
something like this:
```
  if $install_java {
    class {'java':
      distribution => 'jdk',
      version       => $java_version,
    }
  }
```
with appropriate changes to the interface and the ::params class to support passing this key in for use.  

Thanks,
-- Hugh Esco

**Comment by jhoblitt** [comment]
The expectation in this case is that the use would set `install_java => false` and manage the dependency on their own.  This is much more flexible approach then trying to support all possibly configurations via the class's API.

**Comment by hesco** [comment]
See, please:  https://github.com/jenkinsci/puppet-jenkins/issues/455
