### ISSUE TITLE
Unable to upgrade module when using "puppet module upgrade"

### ISSUE THREAD

**Issue by llopezsugar** [jenkinsci/puppet-jenkins#316]
If for some reason someone has the latest version of puppetlabs-apt installed, then the dependencies of the latest version of this module cannot be installed at the moment.

Seems that on the updated metadata.json the version related to the puppetlabs-apt module will need to be updated to at least the actual version 2.0.1.

Is there any reason that the version 2.0.1 of puppetlabs-apt may not fit the requirements or affect the actual deployment of version 1.4.0?

My actual use case is that I'm installing a new orchestration system that is being managed from Puppet and I cannot use the latest version of this module.

**Comment by llopezsugar** [comment]
PR created just in case:

https://github.com/jenkinsci/puppet-jenkins/pull/317

**Comment by rtyler** [comment]
Do you have a stacktrace or error for this? I'm not sure I entirely understand why this is causing problems

**Comment by llopezsugar** [comment]
Initially this is the error that I'm receiving:

```
puppet module upgrade rtyler-jenkins --modulepath modules
Notice: Preparing to upgrade 'rtyler-jenkins' ...
Notice: Found 'rtyler-jenkins' (v1.3.0) in /.../modules ...
Notice: Downloading from https://forgeapi.puppetlabs.com ...
Error: Could not upgrade module 'rtyler-jenkins' (v1.3.0 -> latest)
  There are 1 newer versions
    No combination of dependency upgrades would satisfy all dependencies
    Dependencies will not be automatically upgraded across major versions
    Upgrading one or more of these modules may permit the upgrade to succeed:
    - puppetlabs-stdlib
    - puppetlabs-apt
    - puppetlabs-java
    - darin-zypprepo
    - nanliu-staging
    Use `puppet module upgrade --force` to upgrade only this module
```

This issue happens because I've installed the module puppetlabs-apt before rtyler-jenkins so the system is installing the latest version at this moment of puppetlabs-apt (v2.0.1) and then doesn't permit to upgrade the actual version of rtyler-jenkins (v1.3.0)

**Comment by llopezsugar** [comment]
@rtyler I've implemented my configuration using librarian-puppet to control the dependencies better in our installation. Based on this, the version installed of puppetlabs-apt will be v1.8.0. 

In that way there's no problem to use the module.

In other hand if you give me the green light I would like to propose the code for using the latest version of puppetlabs-apt as it seems a bit more reliable on handling the keys/sources from packages.

**Comment by madAndroid** [comment]
We're also experiencing this issue; the symptoms are slightly different - when we've got other modules in the Puppetfile which reference `'puppetlabs-apt', '>= 2.0.0'`, the dependency resolution fails, and the installation fails. Is there any specific reason `puppetlabs-apt` is being pinned to `1.8.0`?

**Comment by llopezsugar** [comment]
@madAndroid I've verified the code and the initial issue is related to how the `rtyler-jenkins` module uses APT to install the packages. Since version 2.0.0 of `puppetlabs-apt`, some of the ways to declare the sources changed, therefore if you want to install version 1.4.0 of this module, then you will need to install puppetlabs-apt version 1.8.0.

In my previous comment I've asked @rtyler if it's ok to propose the adaptation of the necessary classes in order to be able to use `puppetlabs-apt >= 2.0.0`, but so far didn't received an answer and didn't wanted to come with proposed code and being invasive on the development of this module.

**Comment by madAndroid** [comment]
There are existing PRs for this at #281 and #301, which address the changes required for supporting puppetlabs-apt > 2.0.x - perhaps these PRs can be consolidated to address the issue ( cc @jhoblitt )

**Comment by llopezsugar** [comment]
@madAndroid I've checked @jhoblitt PR and seems a very good change. Additionally to this I saw the comment in the conversation about the upgrade of `puppetlabs-apt` but just in case wanted to collaborate and updated PR https://github.com/jenkinsci/puppet-jenkins/pull/317 with also a bit of refactor in order to not to repeat Keys and URL's in the conditions. (cc @tedivm to be aware)

**Comment by llopezsugar** [comment]
Puppetlabs-apt Module was updated to be backward compatible for declaration of Sources .

Closing this one as is not relevant anymore (Unless someone wants to change the format to the version 2.x)
