### ISSUE TITLE
CLI classes unaware of Jenkins' --prefix

### ISSUE THREAD

**Issue by drewhemm** [jenkinsci/puppet-jenkins#357]
When one configures Jenkins to run with a prefix, e.g. fqdn:8080/jenkins, the CLI classes currently have no way of following this prefix and therefore are unable to communicate with the running Jenkins instance. The URL is hardcoded in cli.pp and cli_helper.pp.

**Comment by jhoblitt** [comment]
The URL is generated here: https://github.com/jenkinsci/puppet-jenkins/blob/master/manifests/cli.pp#L57

Do you not want `localhost` in /etc/hosts or do you want to run jenkins without it listening on the loopback?

**Comment by drewhemm** [comment]
The problem is not the domain, but the path. When Jenkins is running on http://localhost:8080/jenkins, the CLI tries to reach it on http://localhost:8080

I'm experimenting with creating a jenkins_prefix function in the same way as the current jenkins_port function to pull the value out of the config_hash...

**Comment by bigmyx** [comment]
Seems like I still have this issue, even with the latest version: CLI does not seems to pick up the prefix and trying to connect by http://localhost:8080.
My class import looks like this:
```
  class { 'jenkins':
    cli          => true,
    user         => $jenkins_user,
    group        => $jenkins_user,
    manage_user  => false,
    manage_group => false,
    executors    => 8,
    config_hash => {
     'PREFIX' => { 'value' => "/$hostname" },
     'JENKINS_USER' => { 'value' => $jenkins_user },
     'JENKINS_GROUP' => { 'value' => $jenkins_user },
    }
```
As I understand `jenkins_prefix()` function should lookup the prefix in `config_hash`  ?

Please advise.
