### ISSUE TITLE
plugin config where plugin uses hudson.util.Secret

### ISSUE THREAD

**Issue by sfhardman** [jenkinsci/puppet-jenkins#364]
I need to set up config for some plugins (e.g. "stashNotifier") that store a password in the config with hudson.util.Secret.  Is there anything in this module to support putting an encrypted password into a config based on a plaintext password, or do I need to be looking at something else (e.g. run a groovy script)?

Thanks

**Comment by cdenneen** [comment]
@sfhardman what was solution for this?

**Comment by sfhardman** [comment]
I'm not sure why I closed this, as I didn't find a solution I was really happy with.  

It looks like you should be able to encrypt with Groovy using the command line API, but I haven't had a chance to have a good look into it yet.  Something like:

```
import hudson.util.Secret
def secret = Secret.fromString('my password')
println(secret.getEncryptedValue())
```
