### ISSUE TITLE
jenkins user and jenkins_home directory not configurable

### ISSUE THREAD

**Issue by omar952** [jenkinsci/puppet-jenkins#365]
Hi,

It seems that the jenkins main manifest to install jenkins master, creates a OS level user named "jenkins" with a home directory of "/var/lib/jenkins". The OS user and home directory are not configurable. I believe this has been done because the yum package to install Jenkins, always installs the master to the /var/lib/jenkins directory.

In my scenario, I have a jenkins user that I have created myself prior to running this manifest which has a home directory of /home/jenkins. Jenkins master is still installed in /var/lib/jenkins, however, this means that jenkins plugins are reinstalled everytime the puppet script is run, as lib/puppet/jenkins.rb always looks in "~jenkins" to find the plugins directory, which in my case does not exist. 

My change request would be to allow the OS user and its home directory, as well as the Jenkins home directory to be configurable, so that these can be set by the module user.

Thanks

**Comment by tstibbs** [comment]
Note that afaics if installing on something that uses RPMs (CentOS in my case), jenkins **always** gets installed into `/var/lib/jenkins`, regardless of what you set in puppet. So in this case (i.e. on a rhel derivative) `jenkins.rb` is simply wrong, it should just look in `/var/lib/jenkins`.
