### ISSUE TITLE
tool_locations doesn't work

### ISSUE THREAD

**Issue by patcadelina** [jenkinsci/puppet-jenkins#366]
When defining a tool location as:

    class { 'jenkins::slave':
        slave_name     => 'slave_1',
        ...
        tool_locations => 'System-CPython-2.7:/usr/bin/python2.7'
    }

Puppet complains that:

    "-toolLocations" is not a valid option

**Comment by jhoblitt** [comment]
What version of the module and puppet are you using?

**Comment by jhoblitt** [comment]
Could you post the complete error message?  I suspect the error your seeing is not coming from puppet itself.

**Comment by patcadelina** [comment]
Versions:

    // from metadata.json
    "name": "rtyler-jenkins",
    "version": "1.5.0",

    $puppet --version
    2.7.11

Error message:

    "-toolLocations" is not a valid option
     -autoDiscoveryAddress VAL      : Use this address for udp-based auto-discovery
                                      (default 255.255.255.255)
     -candidateTag VAL              : Show swarm candidate with tag only
     -description VAL               : Description to be put on the slave
     -disableClientsUniqueId        : Disables Clients unique ID.
     -disableSslVerification        : Disables SSL verification in the HttpClient.
     -executors N                   : Number of executors
     -fsroot FILE                   : Directory where Jenkins places files
     -help (--help)                 : Show the help screen
     -labels VAL                    : Whitespace-separated list of labels to be
                                      assigned for this slave. Multiple options are
                                      allowed.
     -master VAL                    : The complete target Jenkins URL like
                                      'http://server:8080/jenkins/'. If this option
                                      is specified, auto-discovery will be skipped
     -mode MODE                     : The mode controlling how Jenkins allocates
                                      jobs to slaves. Can be either 'normal'
                                      (utilize this slave as much as possible) or
                                      'exclusive' (leave this machine for tied jobs
                                      only). Default is normal.
     -name VAL                      : Name of the slave
     -noRetryAfterConnected         : Do not retry if a successful connection gets
                                      closed.
     -password VAL                  : The Jenkins user password
     -passwordEnvVariable VAL       : Environment variable that the password is
                                      stored in
     -retry N                       : Number of retries before giving up. Unlimited
                                      if not specified.
     -showHostName (--showHostName) : Show hostnames instead of IP address
     -t (--toolLocation)            : A tool location to be defined on this slave.
                                      It is specified as 'toolName=location'
     -tunnel VAL                    : Connect to the specified host and port,
                                      instead of connecting directly to Jenkins.
                                      Useful when connection to Hudson needs to be
                                      tunneled. Can be also HOST: or :PORT, in
                                      which case the missing portion will be
                                      auto-configured like the default behavior
     -username VAL                  : The Jenkins username for authentication

**Comment by rtyler** [comment]
I think what might be useful as well is knowing which version of Jenkins (or the CLI specifically) you're experiencing this issue with

**Comment by patcadelina** [comment]
I'm running Jenkins 1.628, CLI version is 1.628 as well.

**Comment by jhoblitt** [comment]
#367 Should resolve this issue.
