### ISSUE TITLE
slave:  INFO: Failure authenticating with BASIC 'Jenkins'  401

### ISSUE THREAD

**Issue by iakovgan** [jenkinsci/puppet-jenkins#371]
I had an error: 

```
INFO: Failure authenticating with BASIC 'Jenkins'@MYJENKINS
Failed to fetch slave info from Jenkins CODE: 401
```
It turned out that swarm-client requires password to be single quoted (even if no special character used)
http://echelog.com/logs/browse/jenkins/1401228000

The workaround is trivial: 
``` yaml
jenkins::slave::ui_user: "'USER'" # keep single quotes
jenkins::slave::ui_pass: "'PASSWORD'" # keep single quotes
```

Can it be included into the template?

**Comment by jhoblitt** [comment]
It would probably be better to change the template to use single quotes:

https://github.com/jenkinsci/puppet-jenkins/blob/master/templates/jenkins-slave-defaults.erb#L58-L59

**Comment by iakovgan** [comment]
Yes. Adding single quotes to the template is the best solution i guess.

**Comment by rtyler** [comment]
@iakovgan if you want to make a quick, PR I'll merge it happily, otherwise I'll get to this over the weekend :)

**Comment by iakovgan** [comment]
@rtyler Here is the pull request: https://github.com/jenkinsci/puppet-jenkins/pull/374
