### ISSUE TITLE
Slave: swarm-client requires a cashe directory /home/jenkins-slave/.jenkins/ 

### ISSUE THREAD

**Issue by iakovgan** [jenkinsci/puppet-jenkins#372]
swarm-client requires a cashe directory /home/jenkins-slave/.jenkins/, owned by swarm-client. It would be nice to create it automatically.    

swarm-client-1.22-jar-with-dependencies.jar

**Comment by rtyler** [comment]
@iakovgan is the swarm-client not creating it automatically? if so then I definitely agree

**Comment by iakovgan** [comment]
Sorry. My bad. 
Swarm-client is creating it automatically. It was just some bug with access rights.
