### ISSUE TITLE
Credential types

### ISSUE THREAD

**Issue by cs278** [jenkinsci/puppet-jenkins#373]
I'm trying to configure the GitHub plugin using Puppet as part of that I need to provide a credential for the API token which requires a 'secret text' credential, currently this is not possible using this module.

Would it not be better to add a defined type for each kind of credential rather than one cluttered type?

Also `jenkins::credentials` really should be `jenkins::credential`, seems there is a PR to address this #311.

**Comment by georgemihalcea** [comment]
I am also trying to configure a plain text credential to store a GitHub token in it and there is no such option. It would be useful.

**Comment by jhoblitt** [comment]
@cs278 @georgemihalcea I am actively using/contributing to the `github-oauth` plugin.  I have posted a PR that provides two new types `jenkins_security_realm`/ `jenkins_authorization_strategy` that do support configuring this plugin.  https://github.com/jenkinsci/puppet-jenkins/pull/382  I wouldn't suggest trying it "in production" but it may be worth testing.
