### ISSUE TITLE
Plugins not pinned and updated when using jenkins class

### ISSUE THREAD

**Issue by omar952** [jenkinsci/puppet-jenkins#380]
I have hieradata containing plugin names and versions which I pass to jenkins::plugin type in the same class as I call the jenkins class to install a version of Jenkins. However, I have to run the script twice, as the second run is needed to pin plugins from the bundled version of jenkins and to install the ones I have specified in my hieradata.

Perhaps I am not using the module as intended? Please advise

**Comment by jhoblitt** [comment]
This is a resource ordering problem.  `exec["create-pinnedfile-${name}"]` should come after the plugin is downloaded.
