### ISSUE TITLE
Default to running beaker tests on EC2

### ISSUE THREAD

**Issue by rtyler** [jenkinsci/puppet-jenkins#401]
I spoke with @jhoblitt briefly about this at PuppetConf; the beaker tests I only ever run sporadically because VirtualBox sometimes feels like a nut and sometimes it doesn't

I think we should just default to running them on EC2 and make it clear/easy for developers to set up their local EC2 credentials

**Comment by jhoblitt** [comment]
I'm going to close this since running docker containers under travis has been reliable lately with the exception of centos6 (which others have complained about behaving odd as well).
