### ISSUE TITLE
repo::debian.pp does not work with apt module >= 2.0.0

### ISSUE THREAD

**Issue by neuro42** [jenkinsci/puppet-jenkins#402]
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid parameter key_source on Apt::Source[jenkins] at /etc/puppet/modules/jenkins/manifests/repo/debian.pp:22

As per the 2.0.0 changelog:
 key_source - This parameter was removed. Use key => { 'source' => <source> } instead.

**Comment by rtyler** [comment]
Good catch, I'm wondering if we can correct this without breaking backwards compatibility :/

**Comment by jhoblitt** [comment]
This is the same issue as #359.  I believe it's only version `2.0.0` that has the breaking API change.  `2.1.0` was supposed to restore backwards compatibility.  I don't think metadata.json will let us express this.

**Comment by rtyler** [comment]
D'oh! I didn't notice that in the changelog @jhoblitt sorry. If we can't express this via `metadata.json` at the very least we can make this clearly documented (which would resolve these bugs).

@jhoblitt is it possible to know versions of modules at compile time? so we could have an instructive `err()` message?

**Comment by neuro42** [comment]
One can make use of apt::key earlier than 2.x.  Just use separate key and source resources rather than trying to do both with one

On October 16, 2015 12:58:38 PM PDT, "R. Tyler Croy" <notifications@github.com> wrote:
>D'oh! I didn't notice that in the changelog @jhoblitt sorry. If we
>can't express this via `metadata.json` at the very least we can make
>this clearly documented (which would resolve these bugs).
>
>@jhoblitt is it possible to know versions of modules at compile time?
>so we could have an instructive `err()` message?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/jenkinsci/puppet-jenkins/issues/402#issuecomment-148819629

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by chizou** [comment]
Per @jhoblitt's comment, wouldn't it be more appropriate to rename this bug repo::debian.pp does not work with apt module = 2.0.0? I'm currently using 2.2.0 and it's working, somewhat.

**Comment by jhoblitt** [comment]
@daenney Would you be willing to give some guidance re: #359 & #458 ?  I'd like get the apt issue sorted out but I'm barely familiar with that module.

**Comment by daenney** [comment]
@jhoblitt Just add a version constraint in `metadata.json` to require a newer version of the apt module?

**Comment by jhoblitt** [comment]
@daenney My inclination is to require 2.1+ unless someone objects...

**Comment by rtyler** [comment]
I believe this was fixed with #711
