### ISSUE TITLE
jenkins::job::present issue

### ISSUE THREAD

**Issue by zonArt** [jenkinsci/puppet-jenkins#409]
Is there any known issue with jenkins::job::present resource ? It looks like that if you try to create a job with it, the first run (when job doesn't exist) everything is fine, but then it fails because it tries to create the job again (using jenkins-cli) and it already exists though failing.

I didn't see any `onlyif` or `unless` statement within jenkins-cli create-job command

**Comment by jhoblitt** [comment]
@zonArt It uses the `creates` parameter on the `exec` resource for idempotence.  Could you give us the log output from puppet, and relevant snippet of your manifest, and the versions in use?

**Comment by zonArt** [comment]
Hi,

After a little more analysis, I found why it was not working, there is actually a bug (at least in tag v1.6.0) at line 30 of present.pp where you define `job_dir = ${::jenins::jobs_dir}/${job_name}`. Note that `::jenkins::jobs_dir` param doesn't exist and should be replaced by `::jenkins::job_dir`

**Comment by zonArt** [comment]
PR may follow with some more modification on split of present.pp with split of responsibility

**Comment by zonArt** [comment]
It's actually corrected in version 1.6.1, you can close this issue, sorry
