### ISSUE TITLE
Unable to persist firewall rules: Execution of '/usr/libexec/iptables/iptables.init save' returned 1:

### ISSUE THREAD

**Issue by ltutar** [jenkinsci/puppet-jenkins#424]
I am using PE2015.2
CentOS 7
rtyler-jenkins (v1.6.1)
puppetlabs-firewall (v1.7.1)

I have the following line in yaml:
jenkins::configure_firewall: true

With the first puppet run, I get the following warning:
Notice: /Stage[main]/Jenkins::Firewall/Firewall[500 allow Jenkins inbound traffic]/ensure: created
Warning: Firewall[500 allow Jenkins inbound traffic](provider=iptables): Unable to persist firewall rules: Execution of '/usr/libexec/iptables/iptables.init save' returned 1: 
Notice: /Stage[main]/Jenkins::Cli/Exec[jenkins-cli]/returns: executed successfully

**Comment by queeno** [comment]
Hi @ltutar 

The [puppetlabs-firewall](https://github.com/puppetlabs/puppetlabs-firewall/blob/master/manifests/linux/redhat.pp#L22) module suggests you need to install the `iptables-services` if you're using RHEL/CentOS 7 or Fedora 15.

You should install the package within your manifest:

```puppet
  package { 'iptables-services':
    ensure  => installed,
  }
```

and then I would make sure all the firewall resources automatically require the package before executing:

```puppet
Firewall {
  require => Package['iptables-services']
}
```

**Comment by queeno** [comment]
Hey @ltutar 

I didn't realise this earlier, but it appears that [puppetlabs-firewall](https://github.com/puppetlabs/puppetlabs-firewall/blob/master/manifests/linux/redhat.pp#L35) does actually install `iptables-services` when the firewall class is called (vs the resource).

You could potentially declare both the firewall resource and class:

```
include ::firewall

firewall { 'your rule goes here':
....
}
```

where:
- the `::firewall` class ensures your firewall is up and running and all the dependencies are installed.
- the `firewall` resource creates your firewall rule.

The naming is a bit confusing, but this should eventually do the job!

**Comment by ltutar** [comment]
Thank you for your advice. Adding firewall as class to node group name through console helped. I'll close the issue.
