### ISSUE TITLE
puppet module conflict with camptocamp/archive

### ISSUE THREAD

**Issue by mmarseglia** [jenkinsci/puppet-jenkins#427]
Hi,

  We're running into an issue w/ module namespace conflict on camptocamp/archive.  We use puppetcommunity/archive.

  Has anyone run into this?  How have you worked around it?

**Comment by jhoblitt** [comment]
@mmarseglia There's some features needed by this module that are planned but still absent from `nanliu/archive`.  If your able to, a work around but be to put jenkins master/slaves into their own env.

**Comment by rvincentatprokarmadotcom** [comment]
The last time I submitted a patch for [nanliu/archive](https://github.com/nanliu/puppet-archive), the author redirected me to [puppet-community/archive](https://github.com/puppet-community/puppet-archive).

**Comment by xaniasd** [comment]
Yes, https://github.com/puppet-community/puppet-archive seems to be the one actively maintained. 

@jhoblitt, which features are considered to be show-stoppers? I see allow_insecure, follow_redirects, timeout and proxy_server as features missing from the puppet-community/archive. I managed however, with limited refactoring at plugin.pp, to install the git plugin using the puppet-community module.

**Comment by mmarseglia** [comment]
@jhoblitt thanks for the suggestion.  I have done that with the Jenkins master.  However, all our executors are on jenkins workers.  They require additional software and the puppet modules used to manage that software uses puppet-community/archive.

**Comment by jhoblitt** [comment]
It looks like proxy support was merged into puppet-community/archive yesterday: https://github.com/puppet-community/puppet-archive/pull/83 , which means this module may be able to be migrated to it as soon as there is a stable forge release.

**Comment by jhoblitt** [comment]
@xaniasd FYI, there has never been a forge release of `archive` under the `puppetcommunity` namespace.  Nan is planning to change this at some point but I don't recall what the plan was.  There are existing users of this module that require proxy support that we need to be careful not to break.

**Comment by xaniasd** [comment]
Great! Thanks :)

**Comment by xaniasd** [comment]
FYI: https://forge.puppetlabs.com/puppet/archive

**Comment by jhoblitt** [comment]
Anyone interesting in making a PR for this?

**Comment by elkangaroo** [comment]
This: https://github.com/jenkinsci/puppet-jenkins/pull/433
I hope this gets merged in soon =)

**Comment by jhoblitt** [comment]
#433 needs to be rebased -- anyone interested?

**Comment by mmarseglia** [comment]
@jhoblitt i'll work on it.

**Comment by jhoblitt** [comment]
@mmarseglia I have the ball.  PR should be ready shortly.
