### ISSUE TITLE
Passing an array to jenkins::plugin

### ISSUE THREAD

**Issue by joshuabaird** [jenkinsci/puppet-jenkins#429]
I'm trying to do something like this:

```
$plugins = ['git', 'maven-plugin', 'blah']
jenkins::plugin { "$plugins": }
```

In this scenario, only 'blah' gets installed.  'git' and 'maven-plugin' are ignored and do not get installed.  Is this expected?

**Comment by jhoblitt** [comment]
That snippet is asking for a plugin named "git maven-plugin blah", which I doubt exists... ;)

**Comment by joshuabaird** [comment]
Um, yeah.  You are totally right.  Sorry!
