### ISSUE TITLE
Error: Could not find a suitable provider for jenkins_authorization_strategy

### ISSUE THREAD

**Issue by boydj** [jenkinsci/puppet-jenkins#434]
@jhoblitt  I'm trying to use this, but feel like I must be doing something terribly wrong.

Error: Could not find a suitable provider for jenkins_authorization_strategy

```
class boydj::jenkins::install inherits boydj::jenkins {
  class { '::jenkins':
    install_java => true,
    cli => true,
    repo => false,
    version => installed,
    direct_download => 'puppet:///modules/boydj/rpm/jenkins-1.625.2-1.1.noarch.rpm',
  }

  include ::jenkins::cli_helper

  class { '::jenkins::cli::config':}

  jenkins_authorization_strategy { 'hudson.security.AuthorizationStrategy$Unsecured':
    ensure => 'present',
  }
}
```

**Comment by boydj** [comment]
This looks to be caused by:

  confine :feature => :retries

in lib/puppet_x/jenkins/provider/cli.rb.

I've done a gem install retries, but still not working.

**Comment by boydj** [comment]
Ah, I have now done /opt/puppet/bin/gem install retries and this is working now. Did I miss something in the documentation?

**Comment by jhoblitt** [comment]
@boydj The situation with installing gems to be used by puppet is a bit of a mess right now depending on if the agent is using the system ruby or is vendored (aio/pe packages).  I'm not sure what the best way to handle this [reliably] is.

**Comment by boydj** [comment]
👍
