### ISSUE TITLE
Plugins specified by version number are not updated

### ISSUE THREAD

**Issue by alan-schwarzenberger** [jenkinsci/puppet-jenkins#445]
The commit at cec172003a66168451e2039cca19a57c2985ae05 changed from wget to archive::download to fetch plugins. This has not implemented correctly fetching plugins by version number.

Take for example https://wiki.jenkins-ci.org/display/JENKINS/Multiple+SCMs+Plugin which we download once say at version 0.3. What we actually have downloaded is the file 'multiple-scms.hpi'.
Given the following plugin code
```
jenkins::plugin { 'multiple-scms':
  version => '0.5',
}
```
Subsequent puppet runs construct a download URL http://updates.jenkins-ci.org/download/plugins/multiple-scms/0.5/multiple-scms.hpi, but uses archive::download where the relevant bit of code is https://github.com/camptocamp/puppet-archive/blob/master/manifests/download.pp#L161 
```
exec {"download archive ${name} and check sum":
  command     => "curl ${proxy_option} -s -S ${insecure_arg} ${redirect_arg} -o ${src_target}/${name} '${url}'",
  creates     => "${src_target}/${name}",
```
And because the file exists (remember there is no version number in the filename) we will not download it again.

One way around it is to specify checksums, but the Jenkins update site does not seem to provide checksums (eg *.md5), so there is no easy way to do that as far as I can see. I don't want to manually download and calculate the checksum in order to update my puppet code. Did I miss something there?

I can see a possible approach which would be to parse "Implementation-Version: 0.3" from META-INF/MANIFEST.MF from inside the hpi file. We could perhaps cheat by reading it from plugins/multiple-scms/META-INF/MANIFEST.MF instead which would be cheaper. If that version did not match the requested version then we could delete the relevant hpi file which would force a re-download, getting the dependency order correct so that it all happens in a single puppet run.

Thoughts on this approach before looking at coding it?

**Comment by alan-schwarzenberger** [comment]
Realised that there is already a jenkins_plugins fact
```
jenkins_plugins => ant 1.2, antisamy-markup-formatter 1.1, artifactdeployer 0.29, credentials 1.18, cvs 2.11, external-monitor-job 1.4, git 2.3.4, git-client 1.19.0, gitlab-hook 1.4.1, gitlab-merge-request-jenkins 1.2.2, javadoc 1.1, junit 1.2-beta-4, ldap 1.11, mailer 1.11, matrix-auth 1.1, matrix-project 1.4.1, maven-plugin 2.7.1, multiple-scms 0.3, pam-auth 1.1, ruby-runtime 0.12, saml 0.3, scm-api 0.2, script-security 1.13, ssh-credentials 1.10, ssh-slaves 1.9, subversion 1.54, token-macro 1.10, translation 1.10, windows-slaves 1.0
```
So I could propose a merge request in the coming days that compares plugin::version (ie the requested version) with the value from that fact (which shows what it currently installed), and if they are different, deletes the plugin hpi file to force a re-download.

Current behaviour if someone does not specify a version is I think that the latest version _at the time of first puppet run_ is installed (if the jenkins install itself has not already added a version of that plugin) and then that is never updated. That behaviour will not be changed by this.

For a complete solution we also need to find a way of providing a version=>latest mechanism as requested in #309 without also reverting to the previous wget behaviour of a download on every puppet run. I wonder where Jenkins stores the list of available plugin versions as displayed in the UI, and if we could leverage that?

**Comment by alan-schwarzenberger** [comment]
Closing this issue pending further investigation.

**Comment by robinbowes** [comment]
I think this is *still* a problem. Plugins are not upgraded if installed by version (currently using 23df7764d58aed80b573621b102f82a702217a7a).
