### ISSUE TITLE
Systemd causes puppet idempotency issues

### ISSUE THREAD

**Issue by queeno** [jenkinsci/puppet-jenkins#447]
Hi there

I've noticed this module is not idempotent when using it with systemd.

Every puppet run results in the following message being reported:

```
Notice: Compiled catalog for ci.vagrant in environment prod in 3.57 seconds
Notice: /Stage[main]/Jenkins::Service/Service[jenkins]/enable: enable changed 'false' to 'true'
Notice: Applied catalog in 8.52 seconds
```

I have reproduced it on CentOS 7.1.

**Comment by jhoblitt** [comment]
@queeno What version of puppet are you running?

**Comment by queeno** [comment]
I @jhoblitt 

The puppet version I am using is 4.2.3

I did some digging and turned out the issue occurs on systemd OSes (like RHEL/CentOS 7) only.

In order to determine whether a service is enable within systemd, [puppet issues](https://github.com/puppetlabs/puppet/blob/master/lib/puppet/provider/service/systemd.rb#L52) a `systemctl show --property LoadState --property UnitFileState --no-pager` command and then looks for the value of `UnitFileState`.

I found that - although systemd provides backward compatibility - `UnitFileState` doesn't get populated when using init.d scripts, inducing puppet to think that the service is disabled.

I can think of a couple of ways to fix this problem:

- Rectify the behaviour in puppet so it determines the state of the service in a different way (ie `systemctl is_enabled`)
- Use a systemd configuration file for Jenkins rather than init.d

**Comment by cdenneen** [comment]
I found this bug (https://tickets.puppetlabs.com/browse/PUP-5353) which if you set provider on the service to redhat it will default back to SysV init.

I would propose the change to provider but since this module supports Ubuntu it would need to be constructed in a case statement or some other conditional.

**Comment by jhoblitt** [comment]
@queeno I think that @cdenneen suggestion is the right approach here.  Depending on your perspective this is either a bug in systemd or a limitation in the systemd service provider, but I wouldn't hold my breath for this to get resolved upstream.

**Comment by jhoblitt** [comment]
Anyone want to take a stab at a PR?

**Comment by cdenneen** [comment]
#468 submitted

**Comment by cdenneen** [comment]
#470 supersedes #468
