### ISSUE TITLE
"No checksum for this archive" when installing plugins

### ISSUE THREAD

**Issue by ayashjorden** [jenkinsci/puppet-jenkins#450]
Hi @rtyler ,
I've configured a 'jenkins::plugin_hash" section with various plugins in it.
For some of the plugins I' getting the following error:
```==> jenkins-master: Notice: Scope(Archive::Download[ace-editor.hpi]): No checksum for this archive```

Any plugin that have this error is not getting installed.
What does it mean? how can I fix it?

Thanks,
Yarden

**Comment by jhoblitt** [comment]
This is a notice from one of the modules `puppet-jenkins` depends on.  It is not a warning or error.
