### ISSUE TITLE
Module is missing the Jenkins configuation part

### ISSUE THREAD

**Issue by ayashjorden** [jenkinsci/puppet-jenkins#451]
Hi @rtyler,
The module does give the option to manage Job-s via ```jenkins::job``` class, but There's no option to mange the Jenkins Global configuration(such as global security to enable the Google login usage and email configuration.

I think the solution should be in the form of recommending users to use [scm-configuration-sync](https://wiki.jenkins-ci.org/display/JENKINS/SCM+Sync+configuration+plugin) or another best practice to install global configuration.

Thank you,
Yarden

**Comment by jhoblitt** [comment]
@ayashjorden Please take a look at the "experimental" types and providers.  https://github.com/jenkinsci/puppet-jenkins/blob/master/NATIVE_TYPES_AND_PROVIDERS.md
