### ISSUE TITLE
Jenkins can fail during initial install

### ISSUE THREAD

**Issue by chizou** [jenkinsci/puppet-jenkins#453]
I'm trying to install the Jenkins repo and the Jenkins binary but it will fail on occasion because Puppet sets up the following schedule:
1. Install Jenkins key
2. Install Jenkins package
3. apt-get update

Clearly, the apt-get update needs to be step 2. As mentioned in the puppetlabs [apt module limitation](https://forge.puppetlabs.com/puppetlabs/apt#limitations), apt::update needs to be explicitly called if we want to be able to install Jenkins on the same run as installing the key. Otherwise, we have to wait for another puppet run to install Jenkins.

**Comment by jhoblitt** [comment]
I think control of `apt-get` update is the responsibility of the end-user composing the manifest.
