### ISSUE TITLE
rtyler-jenkins fails to respect install_java => false

### ISSUE THREAD

**Issue by hesco** [jenkinsci/puppet-jenkins#455]
This has frustrated my work today:  

```
  package { [ 'apache-tomcat' ]:
    ensure => present,
  }

  class { 'java':
    package => 'jdk',
    version => '2000:1.7.0_67-fcs',
  }

  class { 'jenkins':
    direct_download => 'http://repo01.example.com/full/path/to/jenkins/jenkins-1.625.1-1.2.noarch.rpm',
    install_java    => false,
  }

```

results in:

vagrant@jenkins:~> rpm -qa | grep jdk
jdk-1.7.0_67-fcs

vagrant@jenkins:~> rpm -qa | grep tomcat
apache-tomcat-7.0-65

vagrant@jenkins:~> rpm -qa | grep java
java-1_6_0-ibm-1.6.0_sr16.4-0.3.1

Testing reveals that neither the jdk, nor the tomcat packages are dragging in the java installation, but that java package comes in as a dependency once I enable the jenkins class invocation.  

Any ideas what I might be doing wrong here?  Is this an issue of `install_java => false` failing to do what I would expect such an attribute to do for me?

Any insight would be appreciated.  

-- Hugh

**Comment by jhoblitt** [comment]
@hesco This is the code that pulls in java. https://github.com/jenkinsci/puppet-jenkins/blob/master/manifests/init.pp#L231-L235  Perhaps your RPM has a dependency?

**Comment by hesco** [comment]
Sorry to have ignored you.  Yes, I believe you are correct here.  We discussed your theory back and forth for a few days, then got interrupted by the holiday schedule.  A coworker finally rebuilt that rpm locally, and this time it includes only the .war file (or at least very little else), permitting us to drop the .war into tomcat and restart the jvm and have it work.  Thank you for your insight on this.
