### ISSUE TITLE
Jenkins Global Configuration

### ISSUE THREAD

**Issue by asadpiz** [jenkinsci/puppet-jenkins#460]
Hi is there a way to configure Jenkins using this plugin? for example is it possible to modify the settings in the "Configure System" page ["<Jenkins IP>:8080/configure"] such as JDK, Git, Artifactory. Jira etc.

I know that these settings are stored in xml files by Jenkins so automating the creation of these Jenkins files via puppet is very doable but I didn't want to do something that is already implemented e.g., In the wiki it is mentioned that we can specify the "number of executor threads". So I thought maybe there is already an (partial) implementation that I can build on.

**Comment by jhoblitt** [comment]
@asadpiz Jenkins' on disk "configuration" is serialized java objects.  As of yet, no one has come up with a way to configure arbitrary jenkins settings (which may store values in multiple files).

The path I've been working on is setting values via jenkins' internal API by passing in groovy snippets.  It should be reasonably easy to build on the existing types and providers work to manage new values.  See:

https://github.com/jenkinsci/puppet-jenkins/blob/master/NATIVE_TYPES_AND_PROVIDERS.md

**Comment by asadpiz** [comment]
Thanks I also explored using API but for plugins that have global configuration (i.e,. artifactory etc) the API didn't seem to have corresponding elements.

So I am thinking about creating templates for the XML files in " /var/lib/jenkins" and then populating these files using these " .erb" templates [Idea from here: https://wiki.jenkins-ci.org/display/JENKINS/Administering+Jenkins].

I know that I may sound stupid or this idea seems senseless to you guys because I've just recently started with Puppet & Jenkins so bear with me :)
