### ISSUE TITLE
plugins_dir and job_dir don't default correctly

### ISSUE THREAD

**Issue by alexjfisher** [jenkinsci/puppet-jenkins#474]
Hi

If you set ```localstatedir``` eg...
```
class { '::jenkins':
  localstatedir => '/data/jenkins'
}
```
I would not expect to also have to set ```plugins_dir``` and ```job_dir```.
But, if you don't, they still default to ```/usr/lib/jenkins/plugins``` and  ```/usr/lib/jenkins/jobs```.

**Comment by vStone** [comment]
```
f5b5f405 (Joshua Hoblitt    2015-10-11 14:15:19 -0700 225)   $plugin_dir = "${localstatedir}/plugins"
f5b5f405 (Joshua Hoblitt    2015-10-11 14:15:19 -0700 226)   $job_dir = "${localstatedir}/jobs"
```

What version of the module are you using? Which distro?

**Comment by alexjfisher** [comment]
Good point!  Latest git version (on OEL6)
It looks like 1.6.1 would work fine.  I think this is a regression caused by https://github.com/jenkinsci/puppet-jenkins/commit/00a90d4d162bca20eb1e04554def4ca45028affb

```jenkins::plugin_dir``` now defaults to ```::jenkins::params::plugin_dir``` which is based on ```::jenkins::params::localstatedir```.
https://github.com/jenkinsci/puppet-jenkins/blob/master/manifests/init.pp#L206
But that's only the default.  If you supply a value for localstatedir, it's not used as part of the default to plugin_dir anymore.
