### ISSUE TITLE
Add support for EnvironmentVariablesNodeProperty

### ISSUE THREAD

**Issue by patcadelina** [jenkinsci/puppet-jenkins#487]
I have a use case of needing to specify environment variables on specific nodes. It seems like [this](https://github.com/jenkinsci/jenkins/blob/e2dccc35572b64f5e602a6b1b3efb517c578872c/core/src/main/java/hudson/slaves/EnvironmentVariablesNodeProperty.java) isn't supported at the moment

**Comment by jhoblitt** [comment]
@patcadelina It is not presently supported.  I'm not sure how one would go about that -- perhaps modify the swarm client to all the env vars to be passed as arguments?

**Comment by patcadelina** [comment]
I was thinking going that route as well until I stumbled upon a dated [issue](https://issues.jenkins-ci.org/browse/JENKINS-5401) in Jenkins. So I'm not sure if this is the right approach. FWIW, this [plugin](https://wiki.jenkins-ci.org/display/JENKINS/EnvInject+Plugin) seems to be needed when configuring node environment variables via Jenkins UI. Do we have a use case of puppetizing Jenkins plugins?

**Comment by jhoblitt** [comment]
@patcadelina `::jenkins::plugin` is able to install plugins.  Envinject setup is part of the job configuration xml.
