### ISSUE TITLE
Circular dependancy when trying to place Java Keystore before using Jenkins module

### ISSUE THREAD

**Issue by FireDrunk** [jenkinsci/puppet-jenkins#489]
We are trying to configure the Jenkins module out of the box with SSL certificates. Our JKS file is located on the Puppet master (in the fileserver share), and is placed before the Jenkins module is run.

This because the file needs to be present before the first start of Jenkins.
But because Jenkins creates the user during the installation, i cannot do this:

```
file { '/opt/ssl/jenkins.jks':
  ensure => 'present',
  owner => 'jenkins',
  group => 'jenkins',
}
```
Because this creates a circular dependancy between this file and the Jenkins installation.

~~The workaround is to create the Jenkins user ourselves and let the Jenkins module 'modify' it afterwards. But this is of course not the way to go.~~ Workaround doesn't work, since the catalog in puppet will still be recompiled with the circular dependancy.

It would be nice if we can let the Jenkins module handle the SSL keystore/certificates.

Do you have any suggestions on this matter?

**Comment by jhoblitt** [comment]
@FireDrunk I suggest you disable creation of the role user/group and manage it yourself.  Eg.

```
manage_user => false,
manage_group => false,
````
