### ISSUE TITLE
The metadata.json does not contain java as dependency

### ISSUE THREAD

**Issue by 030** [jenkinsci/puppet-jenkins#492]
This module requires java but that is not defined in the metadata json

**Comment by rtyler** [comment]
@030 This is intentional as it is desired/possible to not have this module pull in the puppetlabs/java module and to not manage the Java installation on the machine.

To the best of my knowledge there isn't a means of declaring an optional dependency yet, so we expect people to install the java module dependency if they wish to use it.

**Comment by 030** [comment]
@rtyler I can see that java has been set to true in the params but when I issue ```whereis jar``` nothing was returned. It seems that the openjdk does not ship the jar or something. I had to install the oracle jdk to get the jar command on CentOS7

**Comment by jhoblitt** [comment]
@rtyler AFAIK, we still don't have optional dependencies.  The main risk with adding `puppetlabs/java` is a conflict with a user supplied `java` module.  We seem to get pretty get usage feedback on master so I'd be willing to add it as a dep and revert it before the next release if there are complaints.

**Comment by rtyler** [comment]
@jhoblitt I don't know what such an experiment would prove. We already know that people have their own home-grown supplied `java` modules :(


@030 I know that the `openjdk` package definitely supplies the `jar` command. I'm not sure why `whereis` isn't finding it on CentOS. I'm sure that it is there though, perhaps `$PATH` should be updated?

**Comment by jhoblitt** [comment]
It looks like `puppetlabs/java` was added to `metajdata.json` by e738ba13 almost a year ago...

**Comment by jhoblitt** [comment]
Its nice to know that our crack team of maintainers is on the ball...

**Comment by rtyler** [comment]
@jhoblitt huh, I must have missed it when I looked last month. Woops
