### ISSUE TITLE
Experimental types do not have support for Puppet enterprise

### ISSUE THREAD

**Issue by danielpalstra** [jenkinsci/puppet-jenkins#498]
The (experimental) CLI types cannot be used with Puppet enterprise since Puppet enterprise does not have the gem provider. 

```
... (/Stage[main]/Jenkins::Cli::Config/Package[retries]) Provider gem is not functional on this host
```

In my opinion https://github.com/jenkinsci/puppet-jenkins/blob/afd09411424af5d0bb2b32b51517e1ae4e30ef2d/manifests/cli/config.pp#L29 should be made configurable by defining another variable in the `jenkins::cli::config`. Any thoughts?

**Comment by jhoblitt** [comment]
@danielpalstra I'm guessing you need the `puppet_gem` provider for the agent?  I'm unsure of the best way to handle this.  One possibility is to select the gem provider based on facts.

**Comment by petems** [comment]
@danielpalstra What version of PE are you using?

There's a basic idea of the if else logic required on various versions here: https://github.com/hunner/puppet-hiera/blob/master/manifests/params.pp#L28

Having it as a parameter might help in the short term.
