### ISSUE TITLE
Next release on Puppet forge?

### ISSUE THREAD

**Issue by 030** [jenkinsci/puppet-jenkins#535]
```mod 'rtyler/jenkins', '1.6.1'``` seems to be the latest

**Comment by jhoblitt** [comment]
We're getting close to making a `1.7.0` release.  See: https://github.com/jenkinsci/puppet-jenkins/milestones/1.7.0%20-%20Oddjob

**Comment by 030** [comment]
The milestone seems to have been completed, but there is no release. When will the 1.7.0 release be created?

**Comment by jhoblitt** [comment]
@030 When the milestone is completed, which is currently is not.
