### ISSUE TITLE
What archive module should be used?

### ISSUE THREAD

**Issue by 030** [jenkinsci/puppet-jenkins#536]
https://github.com/camptocamp/puppet-archive/blob/master/manifests/init.pp seems incorrect as it does not contain the ```source``` attribute. The puppet run fails when https://github.com/camptocamp/puppet-archive/blob/master/manifests/init.pp is called.

**Comment by jhoblitt** [comment]
https://github.com/jenkinsci/puppet-jenkins/blob/master/metadata.json#L26

We recently migrated because there were several complaints of module name conflicts.
