### ISSUE TITLE
Rebuilding a fully managed jenkins from puppet only

### ISSUE THREAD

**Issue by cdenneen** [jenkinsci/puppet-jenkins#539]
Currently there is nothing here that can manage the master.key, hudson.util.Secret and no defined type to generate password hashes.
So if you want to use different security models for LDAP, AD, etc we would need to pass to this module (maybe using hiera-eyaml) a password string and then have that encrypted and placed in the proper config.xml
Since a fresh build would have all new secrets storing the encrypted hash wouldn't be useful without the key and hudson.util.Secret
So either need a way to use the freshly generated key/secret to turning passwords into hashes and/or would need a way to manage key/secret that get layed down with fresh install.

Anyone have a good option or custom defined type they are using here to generate this? I don't think the cli has these options from what I've read.

The goal here with something like jenkins job builder is to freshly build a working Jenkins without having to login to manage anything (AD binding, jobs, etc)... should be able to hit UI and click build

**Comment by jhoblitt** [comment]
@cdenneen I'm not very keen on copying the on disk encryption secrets around as 1) it makes the data that is being managed fairly opaque and 2) it is difficult to predict the file name that secondary secrets may appears in. 

Have you looked at experimental native types? https://github.com/jenkinsci/puppet-jenkins#experimental-types-and-providers

* The [`jenkins_user`](https://github.com/jenkinsci/puppet-jenkins/blob/master/NATIVE_TYPES_AND_PROVIDERS.md#jenkins_user) type is able to manage passwords.
* The [`jenkins_security_realm`](https://github.com/jenkinsci/puppet-jenkins/blob/master/NATIVE_TYPES_AND_PROVIDERS.md#jenkins_security_realm) type shouldn't be very difficult to extend to supporting the ldap plugin.  There are some stale PRs that could be used for examples of what needs to be changed in the groovy helper.

I bootstrap jenkins instances that auth against github from scratch (not manual intervention) on a daily basis using the native types.

**Comment by cdenneen** [comment]
@jhoblitt Sorry if I wasn't clear. I wasn't necessarily suggesting copying the disk encryption secrets around (this could be an option, there are tons of other modules that people prefer to manage templates, crt, keys, etc... so still might be desirable for some people who want to control what keys are used). 

My suggestion however was more of leaving the dynamic generation of master.key and hudson.util.Secret for every new instance (this keeps things little bit more secure by not copying around keys) but create/use some sort of function that would take a string passed in via hiera possibly (encrypted itself by eyaml or gpg), and use the master.key and hudson.util.Secret to encrypt that string to be used in securityRealm or wherever someone wants (used for augeas updates, etc).
Hope that makes my request for some sort of `jenkins::encrypt` function.

Then one could use something like this sort of mock up:

```
set securityRealm/password jenkins::encrypt("$::profile::jenkins::domainpass")
```

**Comment by jhoblitt** [comment]
@cdenneen If I understand what your asking for, you want a function to create encrypted strings that you would then presumably fish out of debug output so they could be copied into a hiera hierarchy?

We are currently handling encryption/decryption of secrets via the `puppet_helper.groovy`.  This means we don't have to manage the at rest keys, which as I mentioned previously has inherent difficulties, and data from hiera can be treated as the sole source of truth.

**Comment by cdenneen** [comment]
@jhoblitt no i want to have a function to encrypt a string from Hiera (like "mystrongpassword") and write it out to config.xml in the securityRealm/password as the encrypted string

**Comment by jhoblitt** [comment]
@cdenneen functions are evaluated at compile time. Ie., on the puppet master. It wouldn't work without a running jenkins master and violates the principle of a single source of truth, unless you are proposing to reimplement the jenkins cryptography logic, and know the values of `master.key` and any other security namespace, such as `org.jenkinsci.main.modules.instance_identity.InstanceIdentity.KEY`. 

IMHO - it is much easier use plaintext strings which are encrypted/decrypted by the puppet helper.

Here is an example of encryption/decryption of a `UsernamePasswordCredentialsImpl` instance.  Note that in this case we don't even need to instantiate a new `hudson.util.secret` object to set the password as the constructor already handles this for us (however, in some cases we do have to manually create the object).

https://github.com/jenkinsci/puppet-jenkins/blob/master/files/puppet_helper.groovy#L542
https://github.com/jenkinsci/puppet-jenkins/blob/master/files/puppet_helper.groovy#L471

**Comment by cdenneen** [comment]
@jhoblitt I agree with you. I think some people might want to control the keys and secret laid down but I'm okay using the helper. 
I see a bash example of the helper just not sure how that is translated to puppet code (I really don't want to have to write out a script to then execute.)
As I said I want to encrypt plaintext strings (well encrypted in hiera). 
Do you have an example of how you use puppet to use this helper with GitHub auth? (Using bogus creds of course)

**Comment by jhoblitt** [comment]
@cdenneen It needs some re-factoring but see if you can make sense of https://github.com/lsst-sqre/sandbox-jenkins-demo

**Comment by jhoblitt** [comment]
great!
