### ISSUE TITLE
Parameter jenkins::slave::ui_pass not enclosed in quotes.

### ISSUE THREAD

**Issue by madelaney** [jenkinsci/puppet-jenkins#542]
For our Jenkins setup, our passwords (jenkins::slave::ui_pass) contain special characters that cause the user to not get authenticated because the password is escaped by the shell.

For example, a test password of: '8jiks#kjke$jk$gjk#' will not authenticate with our Jenkins server unless we patch 'jenkins-slave-defaults.erb' with the following

```
@@ -55,7 +55,7 @@
 OTHER_ARGS=""
 
 if [ -n "$JENKINS_USERNAME" ]; then
-  CREDENTIALS_ARG="-username $JENKINS_USERNAME -password $JENKINS_PASSWORD"
+  CREDENTIALS_ARG="-username $JENKINS_USERNAME -password '$JENKINS_PASSWORD'"
 fi
 
 if [ -n "$CLIENT_NAME" ]; then
```

Our environment is:

- Jenkins v1.654
- Ubuntu 14.04.03 x86_64

**Comment by jhoblitt** [comment]
It is probably worth investigating if https://docs.puppetlabs.com/puppet/latest/reference/function.html#shellquote would work here, as that would also be able to handle `'`.

**Comment by madelaney** [comment]
@jhoblitt , It looks like shellquotes is already being called.

In [slave.pp](https://github.com/jenkinsci/puppet-jenkins/blob/master/manifests/slave.pp#L143) at line 106, I see the following:
```
$quoted_ui_user = shellquote($ui_user)
$quoted_ui_pass = shellquote($ui_pass)
```

I just got back from holiday so I'll be able to do a little more testing today to see if I can't track this down a bit more.

**Comment by jhoblitt** [comment]
@madelaney are you running from master or 1.6.1?

**Comment by madelaney** [comment]
@jhoblitt , I'm using 1.6.1 but I used master as my reference; sorry in hindsight, I should have referenced the [1.6.x](https://github.com/jenkinsci/puppet-jenkins/blob/release-1.6.x/manifests/slave.pp#L106) branch.

**Comment by jhoblitt** [comment]
@madelaney No worries, this module is overdue for a new release official release.  I'm glad we could get this sorted out.

**Comment by madelaney** [comment]
Sorry but I don't think this is resolved. The issue still persists on the 1.6.x branch.

@jhoblitt, would you be open to a pull request that allows me to set my own version of 'jenkins-slave-defaults.erb' either on master or 1.6.x (your preference).
