### ISSUE TITLE
Jenkins Mirror

### ISSUE THREAD

**Issue by cdenneen** [jenkinsci/puppet-jenkins#559]
I've setup local artifactory to mirror the updates.jenkins-ci.org.
I'm wondering if @rtyler or someone can help in what would need to be changed in order to plugin installs or anything else refer to this internal mirror rather than hitting public assets.
Depending upon what needs to be changed, adding that ability here in the module would be useful as well.

Thanks

**Comment by jhoblitt** [comment]
Take a look at the [essentially undocumented]  `update_url` param to `::jenkins::plugin`. 

https://github.com/jenkinsci/puppet-jenkins/blob/master/manifests/plugin.pp#L23

PRs to improve the documentation are always greatly appreciated.

**Comment by cdenneen** [comment]
@jhoblitt yes thanks... I found it late yesterday just hadn't had time to close this issue out (at least now you've documented here for someone else who might search for the issue). Thanks!
