### ISSUE TITLE
archive dependency is incorrect

### ISSUE THREAD

**Issue by raghavendrabijjula** [jenkinsci/puppet-jenkins#566]
- the dependency for `archive` module is pointing to https://forge.puppet.com/camptocamp/archive, which is not compatible. It should be https://forge.puppet.com/puppet/archive.

<img width="781" alt="screen shot 2016-04-21 at 5 17 48 pm" src="https://cloud.githubusercontent.com/assets/8362662/14708036/bee7c76c-07e5-11e6-9641-b2bb1b802a87.png">

**Comment by jhoblitt** [comment]
That is correct for `1.6.1`.  It declared  properly on the current master: https://github.com/jenkinsci/puppet-jenkins/blob/master/metadata.json#L26

We are hoping to cut a new release soon.
