### ISSUE TITLE
Does puppet-jenkins support installing plugins with jenkins 2.0

### ISSUE THREAD

**Issue by perzizzle** [jenkinsci/puppet-jenkins#569]
I am trying to puppetize our jenkins master installation. I have jenkins up and running using the jenkins class but I am struggling to get the jenkins plugins installed with puppet. Following the example at https://puppet.com/blog/module-of-week-rtyler-jenkins-continuous-integration-server I have a simple file named jenkins_plugins.pp that contains

``
class jenkins_plugins {
  # This resource default will ensure the Jenkins service
  # restarts automatically after Puppet configures all plugins.
  Jenkins::Plugin { notify => Class[jenkins::service] }
  # Tell Puppet to configure and manage the Jenkins Git Plugin.
  jenkins::plugin { 'git': }
}
``

It validates using puppet parser validate jenkins_plugins.pp so I then run it using puppet apply jenkins_plugins.pp -v. It outputs:

``
Info: Loading facts
Info: Loading facts
Info: Loading facts
Info: Loading facts
Info: Loading facts
Info: Loading facts
Warning: Scope(Jenkins::Plugin[git]): jenkins::plugin::create_user is deprecated and has no effect
Notice: Compiled catalog for hostname in environment dev in 0.80 seconds
Warning: The package type's allow_virtual parameter will be changing its default value from false to true in a future release. If you do not want to allow virtual packages, please explicitly set allow_virtual to false.
   (at /opt/puppet/lib/ruby/site_ruby/1.9.1/puppet/type/package.rb:430:in `block (3 levels) in <module:Puppet>')
Info: Applying configuration version '1461875897'
Notice: Finished catalog run in 0.49 seconds
``

When I go to the web ui and look at installed plugins none are listed.

**Comment by kak-bo-che** [comment]
In order to install a plugin you have to make sure you have all of its *required* dependencies as well. So for the [git plugin](https://wiki.jenkins-ci.org/display/JENKINS/Git+Plugin) it lists:
* credentials (version:1.25) 
* mailer (version:1.16) 
* scm-api (version:1.0) 
* git-client (version:1.19.6) 
* matrix-project (version:1.6) 
* ssh-credentials (version:1.11)

each of these in tern may have their own dependencies which must also be installed. That is what the "by hand" refers to in the [wiki](https://github.com/jenkinsci/puppet-jenkins#installing-jenkins-plugins)

**Comment by jhoblitt** [comment]
In addition to @kak-bo-che explanation about having to manually declare all deps, at present, we don't believe this module to be fully compatible with jenkins 2.x.

**Comment by perzizzle** [comment]
@kak-bo-che Thanks for the help. Is it possible to determine what plugin dependency is causing an install to fail? I tried running puppet with verbose and checked the puppet logs. I didn't see anything. I've manually put together the list of plugins and their dependencies but I'm sure I'll miss something at some point.

**Comment by jhoblitt** [comment]
@perzizzle Try [re]installing the plugin via the www UI and see if it pull down any other plugins.
