### ISSUE TITLE
Would you be tagging a new one soon?

### ISSUE THREAD

**Issue by alex-mesfin** [jenkinsci/puppet-jenkins#570]
Hi,
I am using this module and would like see it tagged in master to get recent changes...

**Comment by elkangaroo** [comment]
Yes, a new version for puppet forge would be great for some of the recent changes.

**Comment by jhoblitt** [comment]
Yes, there is one minor issue remaining in the 1.7.0 milestone.

**Comment by Bigluu** [comment]
Hi. We would need some changes made in the master branch that are not present in the latest version. 
According to the 1.7.0 milestone there are no open issues left. Do you have a time frame for the release of the 1.7.0 version?

**Comment by jhoblitt** [comment]
1.7.0 went out the door!
