### ISSUE TITLE
Facter 3.1 no longer has osfamily, operatingsystemrelease, operatingsystemmajrelease

### ISSUE THREAD

**Issue by vStone** [jenkinsci/puppet-jenkins#571]
If we want to be compatible with facter >= 3.1 and , we'll need some if $::os magic :/

**Comment by jhoblitt** [comment]
This is a PITA because I don't think we're ready to drop support for older versions of facter.  How have other modules handled this?  Resorting to functions

**Comment by james-powis** [comment]
@vStone can you please provide documentation as to the removal of these core facts? Looking at puppet documentation for factor 3.1 these facts are still listed as legacy but present but not output vi the cli facter command.

**Comment by vStone** [comment]
I'm gonna close this for now. I ran into this while trying to fix something else but I totally forgot what that was so I'm gonna assume I made a pebkac here
