### ISSUE TITLE
Update jenkins::slave::labels to be an array.

### ISSUE THREAD

**Issue by madelaney** [jenkinsci/puppet-jenkins#572]
I'd like to suggest that the jenkins::slave::labels param be updated to either take an array or a string. 

The reason for this is our setup uses hiera and we've found that using a string is kind of messy. Using an array and being able to use deep_merge is extremely helpful.

I'm happy to create a pull request if you're open to this.

**Comment by jhoblitt** [comment]
@madelaney +1  I completely agree.

**Comment by jhoblitt** [comment]
To be pedantic, I would be more than happy to accept a PR to implement this proposal.

**Comment by jhoblitt** [comment]
Resolved by #591
