### ISSUE TITLE
Update jenkins::slave::java_args to be an array.

### ISSUE THREAD

**Issue by madelaney** [jenkinsci/puppet-jenkins#573]
I'd like to suggest that the jenkins::slave::java_args param be updated to either take an array or a string. 

The reason for this is our setup uses hiera and we've found that using a string is kind of messy. This is mostly because we have a distributed environment and we want to adjust some arguments based on locale but we want to keep the others uniform.

I'm happy to create a pull request if you're open to this.

**Comment by jhoblitt** [comment]
:+1:
