### ISSUE TITLE
Can't create jobs/creds/plugins after LDAP auth

### ISSUE THREAD

**Issue by rhoml** [jenkinsci/puppet-jenkins#581]
We use Jenkins and get authenticated using LDAP, after setting up LDAP puppet can't manage any other resource in Jenkins.

**Comment by jhoblitt** [comment]
@rhoml I'm afraid this isn't the right place for support with the ldap plugin.  The mailing list or jira are more appropriate (https://issues.jenkins-ci.org/secure/Dashboard.jspa).

**Comment by rhoml** [comment]
Well, I think it is an issue on the puppet-module not in the ldap plugin it self since puppet is not authenticating properly and I don't see a flag to tell puppet to use the right credentials.

**Comment by jhoblitt** [comment]
@rhoml This module uses the CLI jar to speak to jenkins.  The CLI jar uses an ssh private key to speak to jenkins.  If the jenkins security realm / authorization strategy do not grant administrative access to to said ssh private key, it will break this module.  There __is no administrative back door__ in jenkins.  This module does not presently support configuring the ldap plugin.

My suggestion to you is to try to run the CLI yourself to perform an action that requires administrative access such as removing a job.
