### ISSUE TITLE
Beaker tests failing, is it a plan to fix them ?

### ISSUE THREAD

**Issue by zonArt** [jenkinsci/puppet-jenkins#588]
Couldn't it be an idea to put them in "allow failure" mode unless fixed ? 
As per now, it makes it hard to see if the modification done on a PR is affecting the overall tests or if it is "just" these docker/beaker tests (I'm not really sure about how to call them but I guess you get the point) that are still failing

**Comment by jhoblitt** [comment]
This was more or less resolved by #611
