### ISSUE TITLE
Experimental Resource Types not working on Java Puppetmaster (jRuby)

### ISSUE THREAD

**Issue by elconas** [jenkinsci/puppet-jenkins#597]
Currently Puppetserver (Java Version) does not support "puppet_x" library extensions: 
- See https://tickets.puppetlabs.com/browse/SERVER-973

Therefore I can not use native resource types (e.g. jenkins_credentials {  ... }) on jRuby PuppetServer installations (e.g. 4.0): 

Error Message: 

```
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not autoload puppet/type/jenkins_credentials: no such file to load -- puppet_x/jenkins/type/cli on node jenkins.example.com
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

**Comment by cprice404** [comment]
There is a workaround listed in the ticket that you linked; hopefully you just need to add the agent's "cache/lib" directory to the Ruby load path for Puppet Server.

**Comment by elconas** [comment]
Similar issue in https://github.com/jenkinsci/puppet-jenkins/issues/526

**Comment by elconas** [comment]
I don't really understand this. We are ussing Puppetserver 1.1.3 and there is no "ruby-load-path:" setting. 

I also don't understand how I sould add the agent's cache/lib directory, as it is a Puppetserver issue (Error 400 on the server) 

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not autoload puppet/type/jenkins_credentials: no such file to load -- puppet_x/jenkins/type/cli on node
```

So the puppetserver (using directory environments) is no puppet agent (or at least not a Jenkins client), and I don't see how I can add the directory here.

**Comment by cprice404** [comment]
Look at [Josh's comment in that thread](https://tickets.puppetlabs.com/browse/SERVER-973?focusedCommentId=224547&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-224547) .

Historically, the puppet master included the puppet agent's lib directory in it's ruby load path.  When the agent *on* the master machine runs, it pluginsyncs files into the agent libdir, and then they become available for the master to load.  We consider this to be undesirable behavior but we don't have a long-term fix in place yet, so, for modules that rely on that behavior, the workaround is to add that path to the ruby-load-path in puppetserver.conf.

**Comment by elconas** [comment]
Please wait. We have a puppetmaster, that MAY be running a puppet agent, but it also may also not. For sure the puppetmaster, if beeing a puppet agent also, does not require the jenkins module, and thus it is definitely not plugin synced. The puppetmaster may have the camptocamp/puppetserver module pluginsynced, agreed but not the jenkins module. The pupeptmaster is just SERVING the jenkins module to clients / agents willing to pluginsync it.

The only location for the jenkins/lib/puppet_x is inside of each directory environment (we use dynamic environments!), which I can not add to the ruby-load-path as we have a versioning conflict then (versions of the jenkins plugin may be different in each environment, and thus it must not be a server settings, but a dynamic setting like implemented here: https://github.com/jenkinsci/puppet-jenkins/pull/385

So for me the cleanest solution is to either: 

a) Move the library code to lib/puppet OR
b) merge https://github.com/jenkinsci/puppet-jenkins/pull/385

Regards

**Comment by cprice404** [comment]
Sorry if I wasn't clear - I didn't mean to weigh in on #385 , that change may be totally appropriate and may be more forward-compatible than the workaround I mentioned.  I just wanted to point out that the ticket you linked includes a workaround.

**Comment by elconas** [comment]
From my perspective, the workaround fixes the issue with java based puppet agent, but not the server issue. Correct ?

**Comment by cprice404** [comment]
The workaround is *only* relevant to the server, and specifically to a server that also has an agent running on it so that it can pluginsync the content and make it visible to the server during catalog compilation.

**Comment by jhoblitt** [comment]
I have been contemplating renaming `PuppetX::Jenkins` -> `Puppet::X::Jenkins` as a solution that does not force the end user to modify their master configuration.  I'm not sure what else we can do from the module end?

**Comment by elconas** [comment]
This sounds like a great plan ! This should also be compatible with directory environments. And it makes https://github.com/jenkinsci/puppet-jenkins/pull/598 obsolete (as native providers do the job already).

**Comment by elconas** [comment]
Still one feedback to @cprice404. Do I conclude correctly: 

The workarond works if:
  - the puppet master is also a puppet client, connecting to itself
  - all machines use the same environment
  - directory environments (1 git branch per environment) are *not* in place.

It is not compatible with directory environments (e.g. each git branch is a puppet environment)

Correct ?

**Comment by elconas** [comment]
@jhoblitt Maybe you can discuss this workaround here: https://tickets.puppetlabs.com/browse/SERVER-973 to get this confirmed as "2nd best practice" for puppet custom libraries.

**Comment by cprice404** [comment]
@elconas it's related to https://tickets.puppetlabs.com/browse/SERVER-94 and https://tickets.puppetlabs.com/browse/PUP-4885 and https://tickets.puppetlabs.com/browse/ROAD-180 .

Basically, in today's Puppet:
* The master needs to be able to load the provider in order to compile the catalog
* During compilation the master only looks for files that happen to be in the "lib/puppet" paths, or on the Ruby load path
* This has been an issue for quite some time, and the way that it "worked" in older versions of the master was because the agent on the master would pluginsync the provider .rb files into the agent's libdir, which happened to also be on the ruby load path of the master.
* In Puppet Server we don't include the agent's lib dir on the master's ruby load path by default, though we may change that back because of people having run into this bug - until we get a better long-term fix in place.
* You are correct that the environment that the master's agent is in will affect what files get pluginsynced to that directory on the master, so it is true that during catalog compilation, the provider that gets loaded will be the one that comes from the master's environment
* However, the provider isn't actually used for much during compilation, so as long as the master can load it successfully, things will probably work fine for other agents in different environments when they receive this catalog.  If the different environments have the same version of the module, then things should *definitely* work fine.

Sorry, I know that's all a bit confusing and convoluted.  We're actively working on improving this particular aspect of how environments work.

**Comment by elconas** [comment]
Thanks a lot for clarifying - this is "compliant" with my "puppet universe" :). 

In our case, the puppet master is served by a different puppet master (it is not attached to itself). This puppet master is only serving puppet masters (we have many project specific ones) and we use "prefix" in r10k, so the environments for puppetmaster agents and jenkins agents are different (projecta_master and projectb_master). So I rather wait for "Puppet::X::Jenkins" or https://github.com/jenkinsci/puppet-jenkins/pull/598.

**Comment by elconas** [comment]
How will this go on ? 

Maybe the needed 2.0 compatibility is a good way to cut out all "backward compatibility issues", and create a new branch that fixes all the issues with Puppetserver, duplicate credentials etc. without caring about backward compatiblity. This will then release als 2.x series of the module beeing incompatible with 1.x, but Puppetfile users can pin.

**Comment by cdenneen** [comment]
@jhoblitt Josh, I'm confused. I looked at the puppet ticket and just recently was able to compare my puppetserver.conf and it has already:
```
jruby-puppet: {
    # Where the puppet-agent dependency places puppet, facter, etc...
    # Puppet server expects to load Puppet from this location
    ruby-load-path: [
        "/opt/puppetlabs/puppet/lib/ruby/vendor_ruby",
        "/opt/puppetlabs/puppet/cache/lib"
    ]
```

If I'm reading this correctly the fix was adding that second path (which is already there).
But I'm still getting:

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Resource Statement, Could not autoload puppet/type/jenkins_num_executors: no such file to load -- puppet_x/jenkins/type/cli at /etc/puppetlabs/code/environments/jenkins2/site/profile/manifests/jenkins.pp:21:3
```

**Comment by cprice404** [comment]
@cdenneen thanks for the ping on https://tickets.puppetlabs.com/browse/SERVER-973 .  I've re-opened that ticket and will see what I can do about getting some eyes on it in an upcoming triage session.

**Comment by jhoblitt** [comment]
I'm not hopeful for https://tickets.puppetlabs.com/browse/SERVER-973  to be resolved any time soon. I'm going to change the namespace from `PuppetX::Jenkins` -> `Puppet::X::Jenkins` to work around the problem.
