### ISSUE TITLE
support jenkins 2.x

### ISSUE THREAD

**Issue by bjusufbe** [jenkinsci/puppet-jenkins#603]
This is an example of command that is executed with class jenkins::job:
```
ubuntu@ip-172-30-1-200:~$ cat "/tmp/test_template-config.xml" | java -jar /usr/share/jenkins/jenkins-cli.jar -s http://localhost:8080 create-job "test_template"
java.io.IOException: No X-Jenkins-CLI2-Port among [null, X-Required-Permission, X-Jenkins, X-You-Are-In-Group, X-Hudson, Content-Length, Expires, X-You-Are-Authenticated-As, X-Permission-Implied-By, Set-Cookie, Server, X-Content-Type-Options, Date, X-Jenkins-Session, Content-Type]
	at hudson.cli.CLI.getCliTcpPort(CLI.java:284)
	at hudson.cli.CLI.<init>(CLI.java:128)
	at hudson.cli.CLIConnectionFactory.connect(CLIConnectionFactory.java:72)
	at hudson.cli.CLI._main(CLI.java:473)
	at hudson.cli.CLI.main(CLI.java:384)
	Suppressed: java.io.IOException: Server returned HTTP response code: 403 for URL: http://localhost:8080/cli
		at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1628)
		at hudson.cli.FullDuplexHttpStream.<init>(FullDuplexHttpStream.java:78)
		at hudson.cli.CLI.connectViaHttp(CLI.java:152)
		at hudson.cli.CLI.<init>(CLI.java:132)
		... 3 more
```
This issue happens when latest Jenkins version 2.9 is installed. I've googled around to find out this was not a problem with Jenkins version prior to 2.x. 
Therefore, I've used following class declaration to install Jenkins version: 1.650:
```
class { 'jenkins':
   version => '1.6.50',
}
```
However, this is not possible as we are unable to install any version (other than latest) from jenkins deb repository

Therefore, problem is following:
1. When using latest jenkins version, I'm unable to create job
2. When I try to use jenkins version prior to 2.x, I'm unable to install it

Don't see any workaround available with this plugin currently. Let me know if you think otherwise.
Thanks,
Bakir

**Comment by jhoblitt** [comment]
`1.6.50` is not a valid version...

**Comment by bjusufbe** [comment]
Sorry, meant to say: 1.650
http://pkg.jenkins.io/debian/

Only solution that I see now is to manually wget specific version and use dpkg to install it. However, when using module itself, that is not possible

**Comment by jhoblitt** [comment]
* What version of this module are you using?
* Could you post your complete jenkins manifest?
* Could you post the log output from the installation of `1.650` package failing?

The acceptance tests are passing on ubuntu 14.04, which uses the debian apt repo.  See:

https://travis-ci.org/jenkinsci/puppet-jenkins/jobs/136301336

**Comment by vStone** [comment]
Maybe just use the LTS version then in stead of pinning to a specific version.

```puppet
class {'::jenkins':
  lts => true,
}
```

**Comment by Hasjamesn** [comment]
lts is now at 2.7.1, therefore using the option @vStone is suggesting may no longer work. It looks like pinning to a version is the only option now.

**Comment by jhoblitt** [comment]
I am actively looking at supporting 2.x. https://github.com/jenkinsci/puppet-jenkins/pull/611  The main issue that needs to be dealt with is that 2.x doesn't ship with any plugins, which breaks the puppet helper as it assume a core set of classes are available.

**Comment by jhoblitt** [comment]
@vStone BTW - LTS has been the default on master for a couple of months: https://github.com/jenkinsci/puppet-jenkins/pull/576

**Comment by jhoblitt** [comment]
Actually, I'm going to close this issue since the requester hasn't responded and it is turning into a dup of #575
