### ISSUE TITLE
Active maintenance 

### ISSUE THREAD

**Issue by tphoney** [jenkinsci/puppet-jenkins#605]
I am just wondering about the status of this module. There seem to be a number of PR's waiting to be merged and issues answered. Is this still under active development there was going to be a new release to the puppet forge some time soon ?

**Comment by jhoblitt** [comment]
I'm not sure if 15 days of no commits really counts as dead...  The answers to your questions are yes, yes, and yes. ;)

**Comment by tphoney** [comment]
@jhoblitt i had got a few queries about the module on the forge, i was just relaying them. apologies, i did not want to seem rude. 
having re-read my initial comment. sorry

keep up the good work !!!
