### ISSUE TITLE
Update plugins before adding new?

### ISSUE THREAD

**Issue by stevenpost** [jenkinsci/puppet-jenkins#61]
Hi,

Is there a way to update the default plugins in jenkins before adding additional ones using puppet? Specifying them again in puppet with a version does not work.
I ran into this issue [1].
Basicly the installed version of 'credentials' is incompatible with the 'git' plugin, and thus jenkins refuses to start. Manually removing the git plugins + jenkins restart + plugin update, solves the issue. But there has to be a better way to handle this.
Can this be done using a custom parameter on the jenkins class perhaps, or something else?

The Jenkins version I used is the latest LTS at time of writing (1.509.4), perhaps this doesn't occur with the latest (non-LTS) version, but the LTS version looks more geared towards bigger enterprises.

Best regards,
Steven

[1] https://answers.atlassian.com/questions/217427/git-plugin-error-for-stash

**Comment by jhoblitt** [comment]
@stevenpost It's not idiomatic puppet to manage resources that are not declared as part of the manifest.  For example, there's no way (without writing a custom provider) to update all of the packages present on a system without a resource.   I'm also concerned that we'd run into problems with recursive dependencies.

That said, being able to handle recursive dependency resolution for the new plugins your installing would likely fix this problem.  Unfortunately, that is non-trivial task.

**Comment by jhoblitt** [comment]
I'm going to close this feature request as it would be non-idiomatic puppet and extremely difficult to implement.   Lots of good discussion on this issue.
