### ISSUE TITLE
How do I set the Jenkins URL?

### ISSUE THREAD

**Issue by pong-takepart** [jenkinsci/puppet-jenkins#618]
Hello,

How do I set the Jenkins URL through this module? Specifically, it is the field "Jenkins URL" in the "Jenkins Location" section in the "/configure" page. Thank you.

Peter

**Comment by jhoblitt** [comment]
This isn't currently supported. It would require a simple native type and adding getter/setter methods to `puppet_helper.groovy`.

**Comment by pong-takepart** [comment]
I would like to contribute that feature in, but I don't know the innards of the module very well. I'll try , but no promises. Thank you.
