### ISSUE TITLE
Allow slave defaults management to be optional

### ISSUE THREAD

**Issue by madAndroid** [jenkinsci/puppet-jenkins#619]
We set a number of config options in the slave defaults file that don't follow the same structure as the current template - would you be open to allowing the management of the defaults file to be configurable? This would mean that we can use our own template, and manage the file outside of the scope of the slave manifest

**Comment by madAndroid** [comment]
Alternatively, it may make more sense to make the location of the template configurable.

**Comment by jhoblitt** [comment]
I think allow alternative templates would be pretty reasonable.

**Comment by madAndroid** [comment]
This is no longer required, the config options we were setting have now been exposed in the main template.
