### ISSUE TITLE
Allow virtual jenkins host

### ISSUE THREAD

**Issue by giuliana-bezerra** [jenkinsci/puppet-jenkins#630]
A host parameter for jenkins class would be handful  for people using virtual hosts. A way of providing a private IP rather than using "http://localhost" would support a Vagrant approach  to create jenkins host.

**Comment by jhoblitt** [comment]
Values in the service config file can be overridden with the `config_hash` param.  Something like this should work:

```
  class { 'jenkins':
    config_hash => {
      'JENKINS_LISTEN_ADDRESS' => { 'value' => '1.2.3.4' },
    }
  }
```
