### ISSUE TITLE
jenkins::plugins doesn't work properly with puppet 4.6.2

### ISSUE THREAD

**Issue by telegrapher** [jenkinsci/puppet-jenkins#637]
Hello,

I've recently updated from puppet 4.5 to puppet 4.6 and the plugin installation is not working anymore.
I get the following error:
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Resource Statement, Duplicate declaration: Jenkins::Plugin[credentials] is already declared in file /etc/puppetlabs/code/environments/development/modules/jenkins/manifests/init.pp:267; cannot redeclare at /etc/puppetlabs/code/environments/development/modules/jenkins_master/manifests/init.pp:56 at /etc/puppetlabs/code/environments/development/modules/jenkins_master/manifests/init.pp:56:3 on node jenkins-master
```
It complains that the plugin is declared more than once, but that isn't true. The jenkins_master class is calling the jenkins class and creating a few other additional resources.
There may be an incompatibility with puppet 4.6.2 or maybe there is a bug in the module.

**Comment by telegrapher** [comment]
I'm using the released version 1.7.0

**Comment by vStone** [comment]
The credentials plugin was added to $default_plugins which are installed automatically. Remove this from your own list of plugins to install.

**Comment by telegrapher** [comment]
@vStone Thanks for the tip! Indeed, after taking out the credentials plugin it is working!

I've had to work around a few other duplication issues after this latest puppet update.

There is a secondary effect, I can't control now the version of the credentials plugin without modifying the jenkins module, but that isn't a problem for me.
