### ISSUE TITLE
Credentials plugin hard coded

### ISSUE THREAD

**Issue by madAndroid** [jenkinsci/puppet-jenkins#665]
Hi,

We set a specific version of the credentials plugin, and set that version in our profile module - I've just updated to the latest version of `rtyler/jenkins` and it looks as though this plugin is now being hard coded into the `params.pp`, which means we can no longer control this plugin via our profile module (we're getting duplication error during testing). Is there any way we can make this plugin be optional, defaulting to being installed, and then we can override it in our profile module if we need to?

Thanks in advance.

**Comment by elconas** [comment]
Same issue here. We install jenkins plugins with checksum and version pinned with code around rtyler/jenkins. Now with 1.7.0 credentials plugin beeing managed by rtyler/jenkins and jenkins::params::default_plugins not beeing parametrizable, every puppet run restarts Jenkins, causing long running builds to die ! 

(Again, I don't think this puppet module does semantic versioning right, sorry for the blame)

```
Notice: /Stage[main]/Jenkins::Config/Jenkins::Plugin[credentials]/Archive[credentials.hpi]/ensure: replace archive: /opt/jenkins/data/plugins/credentials.hpi from (sha1)49f4e6386d284bf8468e15bcd279c4a64a37f9ab to (sha1)
Info: /Stage[main]/Jenkins::Config/Jenkins::Plugin[credentials]/Archive[credentials.hpi]: Scheduling refresh of Service[jenkins]
Notice: Notice: /Stage[main]/Jenkins::Config/Jenkins::Plugin[credentials]/File[/opt/jenkins/data/plugins/credentials.hpi]/owner: owner changed 'root' to 'jenkins'
Notice: /Stage[main]/Jenkins::Config/Jenkins::Plugin[credentials]/File[/opt/jenkins/data/plugins/credentials.hpi]/group: group changed 'root' to 'jenkins'
Notice: /Stage[main]/Jenkins::Config/Jenkins::Plugin[credentials]/File[/opt/jenkins/data/plugins/credentials.hpi]/mode: mode changed '0640' to '0644'
Notice: /Stage[main]/Jenkins::Service/Service[jenkins]: Triggered 'refresh' from 1 events
```

**Comment by elconas** [comment]
Workaround provided by https://github.com/jenkinsci/puppet-jenkins/pull/675
(set default_plugins = [] and manage yourself)

**Comment by jhoblitt** [comment]
I've run into this myself needing to upgrade the version of `credentials` in an existing install.  The issue is that the native types are dependent upon this plugin and the goal is for the new types to replace many of the current defined types.  I'm not sure what the correct solution is.
