### ISSUE TITLE
'digest_type' default of 'sha1' is causing all plugins to install repeatedly

### ISSUE THREAD

**Issue by nick-george** [jenkinsci/puppet-jenkins#668]
This could be an issue with the puppet/archive module rather than this module.

I'm using the latest versions of both this and the archive modules and each time I run puppet,  all jenkins plugins are re-downloaded and re-installed. 

    Notice: /Stage[main]/Jenkins::Config/Jenkins::Plugin[credentials]/Archive[credentials.hpi]/ensure: replace archive: /var/lib/jenkins/plugins/credentials.hpi from (sha1)91bd47ae96be9ebe199beb820296d2633994dfb0 to (sha1)
    Info: /Stage[main]/Jenkins::Config/Jenkins::Plugin[credentials]/Archive[credentials.hpi]: Scheduling refresh of Service[jenkins]
    Notice: /Stage[main]/Jenkins::Config/Jenkins::Plugin[credentials]/File[/var/lib/jenkins/plugins/credentials.hpi]/owner: owner changed 'root' to 'jenkins'
    Notice: /Stage[main]/Jenkins::Config/Jenkins::Plugin[credentials]/File[/var/lib/jenkins/plugins/credentials.hpi]/group: group changed 'root' to 'jenkins'

I have managed to work around it by manually setting "digest_type" to "none" for all plugins, but this doesn't work for the credentials plugin, which is being installed out of my control. 

The fix mentioned in #665 would allow me to work around the problem I'm experiencing.

**Comment by elconas** [comment]
Fixed by https://github.com/jenkinsci/puppet-jenkins/pull/672
