### ISSUE TITLE
Changelog for 1.7.0

### ISSUE THREAD

**Issue by MEPhoenyx** [jenkinsci/puppet-jenkins#679]
Hi, 

can you add a changelog for this version? 

What has changed? I found the download path for swar-client. Is there more?
Thanks and Regards

Martin

**Comment by jhoblitt** [comment]
Most (but possibly not all) of the changes for 1.7.0 should be in the associated milestone.  https://github.com/jenkinsci/puppet-jenkins/milestone/9?closed=1
