### ISSUE TITLE
Successful installation/setup, unsuccessful login

### ISSUE THREAD

**Issue by FransUrbo** [jenkinsci/puppet-jenkins#681]
After puppet have run, I go to the web page and login. It seems to accept my username/password, but I get:

```
HTTP ERROR 404

Problem accessing /j_acegi_security_check. Reason:

Not Found
```

Looking at a host where I installed Jenkins manually, I see that it have the `~jenkins/war` directory (especially `war/WEB-INF/security/SecurityFilters.groovy`) while the puppet installed one doesn't have that `war` directory..

**Comment by jhoblitt** [comment]
Try google.  Eg, https://stackoverflow.com/questions/9684320/jenkins-j-acegi-security-check#21078846

This sort of configuration issue is beyond the scope of the puppet module.
