### ISSUE TITLE
The job xml is stored in /tmp

### ISSUE THREAD

**Issue by FransUrbo** [jenkinsci/puppet-jenkins#683]
With [part of] a manifest like:

```
        job_hash => {
            'build' => {
                jobname => "Do the Build",
                config  => template("role_jenkins/jobs/build.xml")
            }
        }
```

The file downloaded by puppet ends up in `/tmp/build-config.xml`. If (when!) this host is rebooted, the `/tmp` directory will be cleared, and hence all jobs will need to be downloaded and initiated again.

**Comment by jhoblitt** [comment]
That is only a temp. file used by the module when installing the job.  It is not mark of jenkins' state.
