### ISSUE TITLE
When to drop puppet 3 support?

### ISSUE THREAD

**Issue by jhoblitt** [jenkinsci/puppet-jenkins#708]
puppet 3.x hit EOL at the end of 2016: https://puppet.com/misc/puppet-enterprise-lifecycle

It would be nice to adopt some puppet 4.x features, such as parameter types, in this module.  If you are still using puppet 3.x, it would be great to hear what your migration plans are.

**Comment by vStone** [comment]
https://voxpupuli.org/blog/2017/01/11/migrating-to-puppet4/ would be a good place to start

**Comment by benh57** [comment]
Anyone working on the Puppet 3 -> Puppet 4 type conversions (getting rid of the validate_ calls, etc?) I can potentially submit a PR since i may just rip those out locally...

**Comment by jhoblitt** [comment]
We've dropped puppet 3 support...
