### ISSUE TITLE
Will this module work with Cloudbees Jenkins Enterprise 2.0?

### ISSUE THREAD

**Issue by mmarseglia** [jenkinsci/puppet-jenkins#720]
Hello,

  We're upgrading our Jenkins install to CJE 2.x.  We use this module to manage our Jenkins slaves and install Jenkins plugins on the master.

  If we upgrade our Jenkins to 2.0 can we still use this module to manage those two functions?

**Comment by jhoblitt** [comment]
This module will always work in an upgrade scenario.  There will likely be problems with a new install on Debian (RedHat is fine) due to the debian packaging automatically starting the daemon with the setup wizard enabled.

**Comment by mmarseglia** [comment]
Thank you.
