### ISSUE TITLE
The SSL certificate has expired for https://updates.jenkins-ci.org

### ISSUE THREAD

**Issue by darkmudley** [jenkinsci/puppet-jenkins#726]
The SSL certificate has expired for https://updates.jenkins-ci.org
Jenkins recommend use of https://updates.jenkins.io, instead.
See:    https://issues.jenkins-ci.org/browse/INFRA-1060
Request that default_plugins_host is exposed in init.pp so user can override, please?

**Comment by egouraud-claranet** [comment]
merged thx @jhoblitt ;)
 https://github.com/jenkinsci/puppet-jenkins/pull/727
