### ISSUE TITLE
allow jenkins::repo to run in another stage

### ISSUE THREAD

**Issue by lawre** [jenkinsci/puppet-jenkins#741]
In our environment, we have all our yum repo's being managed in a 'repos' stage. This causes conflict because the jenkins module will be removed in the 'repo' stage, then re-added in the 'main' stage each puppet run.

**Comment by jhoblitt** [comment]
I don't understand what feature is being requested?

**Comment by lawre** [comment]
in init.pp, in this block of code:

```
  if $direct_download {
    $repo_ = false
    $jenkins_package_class = 'jenkins::direct_download'
  } else {
    $jenkins_package_class = 'jenkins::package'
    if $repo {
      $repo_ = true
      include jenkins::repo
    } else {
      $repo_ = false
    }
  }
```

I'd like to change  the `include jenkins::repo` to run at a different stage.  Here's a mock-up for our environment that works well: `class {"jenkins::repo":stage => repos}`

Perhaps add a new parameter:
`$repo_stage = undef`

and replace `include jenkins::repo` with a new conditional in the above block of code:

```
if $repo_stage {
  class {"jenkins::repo":stage => $repo_stage}
} else {
  include jenkins::repo
}
```

**Comment by lawre** [comment]
Here's is a snippit of the "error" we are receiving with every puppet agent run:

Notice: /Stage[**repos**]/Yum/File[/etc/yum.repos.d/jenkins.repo]/ensure: **removed**
Notice: /Stage[**main**]/Jenkins::Repo::El/Yumrepo[jenkins]/ensure: **created**

**Comment by jhoblitt** [comment]
This module does not have a dependency on a module named `yum`, so it looks like you are trying to declare the jenkins repo external to this module.  I think you are looking for the `class { jenkins: repo => false}` param.

**Comment by lawre** [comment]
yea, this is the workaround we ended up using since we already have another yum class managing all our package installs.  Sorry to bother.
