### ISSUE TITLE
puppet_helper.groovy uses deprecated remoting mode

### ISSUE THREAD

**Issue by oc243** [jenkinsci/puppet-jenkins#749]
My puppet config uses the bootstrap script as described in [0]. However, it appears to have been broken by the deprecation of remoting mode [1]. When puppet runs I now get:
```
java -jar /usr/share/jenkins/jenkins-cli.jar -s http://127.0.0.1:8080 -http groovy /usr/share/jenkins/puppet_helper.groovy create_or_update_user admin me@me.com  admin <SSH KEY>

ERROR: This command is requesting the deprecated -remoting mode. See https://jenkins.io/redirect/cli-command-requires-channel
```

It looks as if we now need to use the ssh or http authentication methods in the `create_or_update_user` function of `puppet_helper.groovy`.

[0] https://github.com/jenkinsci/puppet-jenkins#cli-helper
[1] https://github.com/jenkinsci/jenkins/pull/2795

**Comment by elconas** [comment]
This is true for Jenkins >= 2.54 and Jenkins LTS >= 2.46.2

Note: Calling the groovy heler like this works. I don't see the difference:

```
  $helper_cmd = join(
    delete_undef_values([
      '/usr/bin/cat',
      $helper_groovy,
      '|',
      '/usr/bin/java',
      "-jar ${::jenkins::cli::jar}",
      "-s http://127.0.0.1:${port}${prefix}",
      $auth_arg,
      "groovy ="
    ]),
    ' '
  )
```

**Comment by oc243** [comment]
Thanks @elconas. Would be interested ti see your PR :)

**Comment by elconas** [comment]
The pull request is work in progress, as I can not locally test the code. Right now everything looks good, however I need to fix the xtypes to be jenkins version aware.

**Comment by elconas** [comment]
It seems the native types and providers can not easily be ported, as all data is supplied via stdin (json), making it impossible to provide the helper script via stdin, which is a requirement to avoid remoing (See https://github.com/jenkinsci/jenkins/blob/729016989e13632bc980957d05060510efddf41f/core/src/main/java/hudson/cli/GroovyCommand.java#L97-L100)

**Comment by elconas** [comment]
I personally think it is time for a rewrite of rtyler/jenkins based on native types and providers ONLY and for jenkins 2.46.2 and 2.54 onward (new major version). Then all legacy code could be thrown away.

**Comment by jhoblitt** [comment]
It sounds like there's little reason to keep using the cli jar.  It should be possible to replace the cli based providers with something that uses the `/scriptText` end point directly.

**Comment by elconas** [comment]
I found that a valid workaround (as long as CLI and Jenkins are running on the same machine) is to write the puppet_helper.groovy json data to the temporary file instead of stdin (already happening), make it readbale by jenkins and provide the filename as command line parameter transparently. This avoids printing the json data on ps ax output (including credentials, which may be a security risk) and makes groovy work with latest Jenkins non remoting CLI, also with username and password, which allows to AD and LDAP usage (which we do)

**Comment by elconas** [comment]
I updated the pull request after all tests are green into a single commit.

**Comment by uhanisch** [comment]
Great job

**Comment by stefanandres** [comment]
Nice Job, but how is this supposed to work now?
```
classes:
  - jenkins
  - jenkins::security
  - vefirewall

jenkins::security::security_model: full_control
``` 
on a fresh installation will result in:
```
Info: /Stage[main]/Jenkins::Security/Jenkins::Cli::Exec[jenkins-security-full_control]/Exec[jenkins-security-full_control]: Scheduling refresh of Class[Jenkins::Cli::Reload]
Info: Class[Jenkins::Cli::Reload]: Scheduling refresh of Exec[reload-jenkins]
Notice: /Stage[main]/Jenkins::Cli::Reload/Exec[reload-jenkins]/returns:
Notice: /Stage[main]/Jenkins::Cli::Reload/Exec[reload-jenkins]/returns: ERROR: anonymous is missing the Overall/Administer permission
Notice: /Stage[main]/Jenkins::Cli::Reload/Exec[reload-jenkins]/returns: May 10, 2017 4:44:12 PM hudson.cli.CLI$5 run
Notice: /Stage[main]/Jenkins::Cli::Reload/Exec[reload-jenkins]/returns: WARNING: null
Notice: /Stage[main]/Jenkins::Cli::Reload/Exec[reload-jenkins]/returns: java.io.IOException: Stream is closed
Notice: /Stage[main]/Jenkins::Cli::Reload/Exec[reload-jenkins]/returns:         at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.checkError(HttpURLConnection.java:3512)
Notice: /Stage[main]/Jenkins::Cli::Reload/Exec[reload-jenkins]/returns:         at sun.net.www.protocol.http.HttpURLConnection$StreamingOutputStream.write(HttpURLConnection.java:3486)
Notice: /Stage[main]/Jenkins::Cli::Reload/Exec[reload-jenkins]/returns:         at java.io.DataOutputStream.writeInt(DataOutputStream.java:197)
Notice: /Stage[main]/Jenkins::Cli::Reload/Exec[reload-jenkins]/returns:         at hudson.cli.PlainCLIProtocol$EitherSide.send(PlainCLIProtocol.java:175)
Notice: /Stage[main]/Jenkins::Cli::Reload/Exec[reload-jenkins]/returns:         at hudson.cli.PlainCLIProtocol$ClientSide.sendEndStdin(PlainCLIProtocol.java:347)
Notice: /Stage[main]/Jenkins::Cli::Reload/Exec[reload-jenkins]/returns:         at hudson.cli.CLI$5.run(CLI.java:671)
Error: /Stage[main]/Jenkins::Cli::Reload/Exec[reload-jenkins]: Failed to call refresh: java -jar /usr/share/jenkins/jenkins-cli.jar -s http://localhost:8080 reload-configuration returned 6 instead of one of [0]
Error: /Stage[main]/Jenkins::Cli::Reload/Exec[reload-jenkins]: java -jar /usr/share/jenkins/jenkins-cli.jar -s http://localhost:8080 reload-configuration returned 6 instead of one of [0]
``` 

Can you add more documentation?

**Comment by elconas** [comment]
@stefanandres Hi, unfortunately this never worked with this module since jenkins 2.0 is released, as all cli commands fail for Jenkins 2.0. This is due to "secure by default", which means prior to Jenkins 2.0 jenkins was "unsecure" by default. Since 2.0 it is "full_control" per default. Howevber how can puppet use the CLI to create users if there is no bootstrapping user. 

We solved this by using https://wiki.jenkins-ci.org/display/JENKINS/Configuring+Jenkins+upon+start+up and creating a init script that creates the bootstrapping user during startup. This is all in a provate module, "wrapping" rtyler/jenkins.

**Comment by stefanandres** [comment]
I rather seems the new installation without jenkins::security was in unauthentiated mode (when I used http://...:8080 I could do anything without logging in). After executing jenkins::security with full_control, it prompts me to create an initial user, but the CLI will fail (as you explained).

**Comment by elconas** [comment]
@stefanandres I prepared an extended version of the pull request, adding Jenkins 2.0 bootstrapping user support (See https://github.com/jenkinsci/puppet-jenkins/pull/761). Maybe you can try this one (please see README.md in this branch for how to setup bootstrap user).

@jhoblitt How to proceed. Is there anything needed from your side for this pull request to be approved ?

**Comment by stefanandres** [comment]
Okay - the #761 fix seems to work:

```
classes:
  - jenkins
  - jenkins::security

jenkins_password: mypassword

jenkins::security::security_model: full_control
jenkins::cli_remoting_free: true
jenkins::cli_username: puppet
jenkins::cli_password: "%{hiera('jenkins_password')}"
jenkins::bootstrapuser_hash:
  'puppet':
    ensure: present
    email: root@localhost
    password: "%{hiera('jenkins_password')}"
    full_name: 'Puppet bootstrapping user, do not remove'
```

```
Notice: /Stage[main]/Jenkins::Security/Jenkins::Cli::Exec[jenkins-security-full_control]/Exec[jenkins-security-full_control]/returns: executed successfully
```

**Comment by elconas** [comment]
@stefanandres Nice, Great, Thanks. I also try to fix the spec.

**Comment by elconas** [comment]
@jhoblitt So maybe better merge https://github.com/jenkinsci/puppet-jenkins/pull/761 instead as https://github.com/jenkinsci/puppet-jenkins/pull/761 contains some tests (acceptance only) and also fixes the "sshd not enabled by default" issue on latest Jenkins Servers (needed to wort with ssh key authentication on 2.54++ and 2.46.2.++)

**Comment by stefanandres** [comment]
Okay, I won't be able to use this pull request though. When creating a bootstrap user it just wipes my securityrealm.ldap configuration from config.xml after a jenkins restart. So the entire design of creating a local user for using remote-cli won't work when using external users. :/

**Comment by elconas** [comment]
@stefanandres bootstrap users are only needed for local authentication mode (full_access). If you have AD / LDAP, you can use cli_username and cli_password without the bootstrap users.

**Comment by stefanandres** [comment]
@elconas Thanks, but alas the module still deploys a [puppet.bootstrapping.groovy](https://gist.github.com/stefanandres/aaa39f53155283458622996291ab0f14) file which leads to the ldap configuration being wiped upon restart.

This is the configuration I used
``` 
  class {'jenkins':
    install_java      => true,
    cli_remoting_free => true,
    cli_username      => $cli_username,
    cli_password      => $cli_password,
  }
```
(ldap came from augeas)

**Comment by elconas** [comment]
@stefanandres I fixed the code. puppet.bootstrapping.groovy is now only created if bootstrap users is not empty. This should work with your ldap setting now.

**Comment by stefanandres** [comment]
Really appreciate your effort! Which branch is the current one that has all the fixes? https://github.com/elconas/puppet-jenkins/commits/fix_749_withbootstrapuser doesn't seem to have changes since a few days ;-)

**Comment by elconas** [comment]
Yes this one https://github.com/elconas/puppet-jenkins/tree/fix_749_withbootstrapuser, I always rebase and push --force :)

**Comment by stefanandres** [comment]
Ah, okay - yep, this doesn't create the bootstrap file any longer now when no user is defined

**Comment by madAndroid** [comment]
Thank you for this! we need this with our LDAP config as well (managed via Augeas) - will be testing this out extensively, and will give feedback

**Comment by stefanandres** [comment]
After upgrading to the recent apt-4.1.0, the branch no longer works:
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Apt::Source[jenkins]:
  has no parameter named 'key_source'
  has no parameter named 'include_src' at /etc/puppetlabs/code/environments/pp_3875/modules/external/jenkins/manifests/repo/debian.pp:13 on node syseleven.restvlan6.e2h.operations-jenkins```

Can you make this compatible?

**Comment by yetanotherion** [comment]
FYI
it seems prefixing groovy with -remoting may provide a workaround.
{code}
java -jar cli.jar -s http://url -remoting groovy /path/to/groovy
{code}
