### ISSUE TITLE
Is there documentation on how to use hiera + jenkins::plugins?

### ISSUE THREAD

**Issue by wfsaxton** [jenkinsci/puppet-jenkins#765]
Is it possible to document how to use hiera + jenkins::plugins so that we can install jenkins plugins using a hash via hiera?

Right now I'm simply looping through an array + jenkins::plugin but I'm looking for the "right" way to do this.

**Comment by SergK** [comment]
@wfsaxton is this what are you looking for https://github.com/jenkinsci/puppet-jenkins/blob/master/manifests/init.pp#L104-L110 or https://github.com/jenkinsci/puppet-jenkins/blob/master/manifests/init.pp#L260-L272 ?
``

**Comment by wfsaxton** [comment]
Thanks, that solved part of my issue (not knowing what the syntax was for the YAML).

The second issue, though, was how to actually implement it.  I figured it out (jenkins module automatically looks for that variable and installs the plugins accordingly) but I had no idea I didn't need to do anything.  

Is this something that is commonly done in puppet modules that requires no explanation?  Assigning a hard-coded variable into your YAML will automatically get picked up my a module and "do something"?  If so, then I have a bit more to learn about Puppet.  Otherwise, some documentation on how this process works would have been very helpful!

**Comment by SergK** [comment]
In jenkins you have "wrapper" class `jenkins::plugins`
`include jenkins::plugins`

and this wrapper class just calls [1]

`create_resources('jenkins::plugin',$jenkins::plugin_hash)`

So you can work with this class as described in docs:

```
class{ 'jenkins::plugins':
 plugin_hash => {
   'git' => { version => '1.1.1' },
   'parameterized-trigger' => {},
   'multiple-scms' => {},
   'git-client' => {},
   'token-macro' => {},
 }
}
```

OR in Hiera

```
jenkins::plugin_hash:
  'git':
     version: 1.1.1
  'parameterized-trigger': {}
  'multiple-scms': {}
  'git-client': {}
  'token-macro': {}
```

[1]. https://github.com/jenkinsci/puppet-jenkins/blob/master/manifests/plugins.pp

**Comment by wfsaxton** [comment]
Yes, I understand how this particular module works now (thank you everyone) but my remaining question was: is the way "jenkins::plugins" works a common way for modules to iterate over a hard-coded variable array and, therefore, should be something that doesn't need to be documented OR would documenting this in the README.md be appropriate?

In other words: should someone with sufficient knowledge in Puppet be able to "figure this out" or would it be more appropriate to document it more clearly.  If this is common enough module behavior, i can close this out.  If not, then perhaps the README should be updated to explain how to use it.

**Comment by matonb** [comment]
https://docs.puppet.com/hiera/3.3/puppet.html

Automatic lookups have been in Puppet for quite some time.
