### ISSUE TITLE
plugins should not reinstall themselves if they are already installed

### ISSUE THREAD

**Issue by wfsaxton** [jenkinsci/puppet-jenkins#766]
Everytime puppet is run, it seems that every jenkins plugin re-installs itself.  This is a tremendous waste of resources.

This seems obvious, though.  Perhaps this is a 2.X issue and is currently not being worked on?  I'm using Jenkins ver. 2.46.3.

**Comment by vStone** [comment]
I had the same issue with a couple of plugins and in my case the issue was related to the sha sum. I solved it by configuring (the checksum) in hiera for those plugins that gave issues. Is jenkins reinstalling all of them?

**Comment by wfsaxton** [comment]
Yes, all of the plugins appear to have been updated (all timestamps are recent).  It took 800 seconds to update all of the default recommended plugins (behind a proxy) so this is definitely an issue.

**Comment by wfsaxton** [comment]
It's actually doing this with the credentials plugin which is hard-coded inside the jenkins module:

```
Notice: /Stage[main]/Jenkins::Config/Jenkins::Plugin[credentials]/Archive[credentials.hpi]/ensure: replace archive: /var/lib/jenkins/plugins/credentials.hpi from (sha1)62f4876b6f9b1773db8fbdf3e62ce3c8a56e6fc9 to (sha1)
Info: /Stage[main]/Jenkins::Config/Jenkins::Plugin[credentials]/Archive[credentials.hpi]: Scheduling refresh of Service[jenkins]
Notice: /Stage[main]/Jenkins::Config/Jenkins::Plugin[credentials]/File[/var/lib/jenkins/plugins/credentials.hpi]/owner: owner changed 'root' to 'swrjenk'
Notice: /Stage[main]/Jenkins::Config/Jenkins::Plugin[credentials]/File[/var/lib/jenkins/plugins/credentials.hpi]/group: group changed 'root' to 'swrjenk'
Notice: /Stage[main]/Jenkins::Config/Jenkins::Plugin[credentials]/File[/var/lib/jenkins/plugins/credentials.hpi]/seluser: seluser changed 'unconfined_u' to 'system_u'
Notice: /Stage[main]/Jenkins::Config/Jenkins::Plugin[credentials]/File[/var/lib/jenkins/plugins/credentials.hpi]/seltype: seltype changed 'user_tmp_t' to 'var_lib_t'
Notice: /Stage[main]/Jenkins::Service/Service[jenkins]: Triggered 'refresh' from 1 events
```

This can't be normal behavior.  Perhaps there is an issue with changing the owner/group of the plugins' files or something?

**Comment by surcouf** [comment]
According to https://github.com/jenkinsci/puppet-jenkins/issues/738, jenkins user homedir must be set to /var/lib/jenkins (by default) to allow jenkins_plugins facter to work fine.
This facter is used by plugins manifest to check if a plugin has been already installed or not.
Without this information, the jenkins module will always reinstall any plugins...

Change jenkins user homedir from "/home/jenkins" to "/var/lib/jenkins" has resolved this issue.

**Comment by jhoblitt** [comment]
I believe this is fixed on current master.

**Comment by neluvas** [comment]
I am seeing a similar issue with Jenkins LTS. installed plugins are being reinstalled at every puppet run. as mentioned in previous comments configuring the checksum in hiera seems to work but it is far from ideal...and there is also the built in credentials plugin...
the only deviation to the standard install we have is that we had to change the user from jenkins to jenkins_user to avoid a conflict with an existing AD user.

so service is running as "jenkins_user" and its home dir is set to "/var/lib/jenkins".
jenkins_plugins is empty when I run facter -p jenkins_plugins.
