### ISSUE TITLE
Prevents upgrade of puppetlabs-java module to 2.0.0

### ISSUE THREAD

**Issue by leitmedium** [jenkinsci/puppet-jenkins#767]
Currently puppet-jenkins allows puppetlabs-java only to be < 2.0.0, but 2.0.0 has been released. Upgrading puppetlabs-java to the latest version is therefore not possible at the moment.

**Comment by jayniz** [comment]
I, too, wonder!

**Comment by mmoll** [comment]
The same is true for puppetlabs-apt... what are the plans for the next release? Especially related to #772

**Comment by cristianbalan** [comment]
Any news here? :(

**Comment by jhoblitt** [comment]
PR requested.

**Comment by mmoll** [comment]
see GH-801
