### ISSUE TITLE
Release the software in accordance with semantic versioning

### ISSUE THREAD

**Issue by ghoneycutt** [jenkinsci/puppet-jenkins#770]
Hi,

Could you please do a new release? Ideally a release would be done with every merge or set of merges.

Thank you!

**Comment by rtyler** [comment]
@ghoneycutt While I appreciate your desire to see this module released more frequently, this is not the best way to do that. 

As you can see there are a number of pull requests and issues which could use more sets of eyes, RSpec tests, and/or manual testing. Helping to verify the stability of those changes makes it easier for us to release the Puppet module with confidence.

**Comment by ghoneycutt** [comment]
I absolutely agree with you, though once you do merge something, it should then be released.

**Comment by rtyler** [comment]
@ghoneycutt What you describe has nothing to do with [semantic versioning](http://semver.org/), but rather [Continuous Deployment](https://en.wikipedia.org/wiki/Continuous_delivery#Relationship_to_continuous_deployment), a practice we're not following with repository.

If you're interested in helping more this project into a more continuous-deployment-style method of development, we need many more Beaker tests to help validate changes :fireworks:
