### ISSUE TITLE
code deploy fails when we add mod 'rtyler-jenkins', '0.3.1' to puppetfile

### ISSUE THREAD

**Issue by olluri** [jenkinsci/puppet-jenkins#777]
When I try to add mod 'rtyler-jenkins', '0.3.1' to Puppetfile and deploy the code using code manager I gets below error. I am only having issue with this particular forge module. 

[{"environment":"devops","id":807,"status":"failed","error":{"kind":"puppetlabs.code-manager/deploy-failure","details":{"corrected-env-ame":"devops"},"msg":"Errors while deploying environment 'devops' (exit code: 1):\nERROR\t -> Environment \"pre-prod\" contained non-wod characters, ignoring it.\nERROR\t -> Failed to evaluate /etc/puppetlabs/code-staging/environments/devops/Puppetfile\nOriginal exceptin:\nInvalid 'name' field in metadata.json: the field must be a namespaced module name\n"}}]

**Comment by jhoblitt** [comment]
`0.3.1` is absolutely ancient -- I'm not surprised it doesn't work with the current module infrastructure.  Please try a more recent release.
