### ISSUE TITLE
Remove puppetlabs/apt from hard dependencies

### ISSUE THREAD

**Issue by cfoehrdes** [jenkinsci/puppet-jenkins#786]
The `puppetlabs/apt` dependency causes conflicts with other modules and should not be included as hard dependency according to the puppet style https://docs.puppet.com/puppet/latest/style_guide.html#dependencies.

Maybe consider removing it from the metadata or updating it?

**Comment by cristianbalan** [comment]
I agree...

**Comment by mmoll** [comment]
I don't agree, as otherwise at least also the zypprepo dependency woudl need to get removed

**Comment by cristianbalan** [comment]
Then we should upgrade the dependency request to accommodate apt 4 and/or 3 at least.

**Comment by mmoll** [comment]
The current code is indeed compatible with pl-apt 2.1 to the latest released version.

**Comment by cristianbalan** [comment]
Actually, apt must have been sorted as for https://github.com/jenkinsci/puppet-jenkins/commit/0fc14290b68df9736c24a90477fd669d8c145a86. Hopefully, we'll see all this in Puppet Forge soon.

**Comment by jhoblitt** [comment]
I'm closing this as I don't believe there is any action to be taken.
