### ISSUE TITLE
Replace darin/zypprepo with puppet/zypprepo

### ISSUE THREAD

**Issue by cristianbalan** [jenkinsci/puppet-jenkins#798]
> Hi,
> 
> darin/zypprepo is no longer maintained and was previously deprecated. See voxpupuli/puppet-zypprepo#15 for proof.
> 
> The successor is https://forge.puppet.com/puppet/zypprepo which is maintained by the great guys from VoxPupuli.

The guys from Icinga's module have switched over too as for https://github.com/Icinga/puppet-icinga2/pull/306

**Comment by jhoblitt** [comment]
PR requested.

**Comment by mmoll** [comment]
see GH-800
