### ISSUE TITLE
Module puppetlabs/transition required for Debian/Ubuntu nodes

### ISSUE THREAD

**Issue by lgallard** [jenkinsci/puppet-jenkins#799]
Puppet module puppetlabs/transition also is required for Debian/Ubuntu nodes:

`Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Evaluation Error: Error while evaluating a Resource Statement, Unknown resource type: 'transition' at /etc/puppetlabs/code/environments/dev/modules/jenkins/manifests/systemd.pp:26:3 at /etc/puppetlabs/code/environments/dev/modules/jenkins/manifests/slave.pp:222 on node jenkinsslave
`

**Comment by jhoblitt** [comment]
Which is why it is declared in `metadata.json`.  What is being requested in this  issue?

**Comment by lgallard** [comment]
Hi,

To include the required module in the Readme.

Regards,

El 2 sept. 2017 2:28 a. m., "Joshua Hoblitt" <notifications@github.com>
escribió:

Which is why it is declared in metadata.json. What is being requested in
this issue?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jenkinsci/puppet-jenkins/issues/799#issuecomment-326723325>,
or mute the thread

**Comment by mmoll** [comment]
I'd rather delete the "Dependencies" section in the Readme, as long as metadata.json is correct, that's enough, as also versions are included there.
