### ISSUE TITLE
Private key passing issue with Groovy through jenkins pipeline

### ISSUE THREAD

**Issue by hemanthaSN** [jenkinsci/puppet-jenkins#817]
am trying to pass the private key through groovy script : below is the script
Input:
output = sh(returnStdout: true, script: 'set +x; ./bin/create_bmc_host.sh "${AVAILABILITY_DOMAIN}" "${COMPARTMENT_ID}" "${IMAGE_ID}" "${SUBNET_ID}" "${SHAPE}" "${PRIVATE_KEY}" "${USER_OCID}" "${TENANT_OCID}" "${REGION}" "${USER_TIMEOUT}"')

Output : In Jenkins pipeline the parameters are empty
DOMAIN=
COMPARTMENT_ID=
IMAGE=
SUBNET=
SHAPE=
PRIVATE_KEY=
USER_OCID=
TENANT_OCID=
REGION=

Then I changed the above script as below
output = sh(returnStdout: true, script: "set +x; ./bin/create_bmc_host.sh ${AVAILABILITY_DOMAIN} ${COMPARTMENT_ID} ${IMAGE_ID} ${SUBNET_ID} ${SHAPE} ${PRIVATE_KEY} ${USER_OCID} ${TENANT_OCID} ${REGION}")

Output:
DOMAIN=kgzP:PHX-
COMPARTMENT_ID=ocid1.compartment.oc1..aaaaaaaaq5bsc2g5ne7hftodqtdrca
IMAGE=ocid1.image.oc1.phx.aaaaaaaaqutj4qjxihpl4mboabsa27mrp
SUBNET=ocid1.subnet.oc1.phx.aaaaaaaanhnue37m3gpouzhc7vi5o
SHAPE=VM.Standard
PRIVATE_KEY=-----BEGIN
USER_OCID=PRIVATE
TENANT_OCID=KEY-----nMIIEwAIBADANBgkqhkiG9w0BAQEFAASCBKowggSmAgEAAoIBAQC4cQsgrfMIyC6DnwfeKOJTJgagHp39dC2djxr+ivf02MXmPrtlVypGngwlcNNgn0AYISDqUPmsl7QU/n0bBRm/Vs9ZXXUU78inEujhRYP8kNUeoD+......................................................................................bRhRl4FnHe1Q5quyakoyG+1rjuk4j4vQhfl+cw6xfSGSFfYsSskCgYEA4GajBLD2pjU4ePkVnqVXAUAoZ66w4aLSeoLD/zALY9wzHTVSY4y8dSZOt8+Mqgmv/1OYOanTC+yMz7p+0KrGRuqPgZpziFobNfLvTDzQu2z5E5dwXztV1f+1tHaeTkp9Wk1R3pdnNYOs6jU44JuZlbef42/2bs0g3Gg=n-----END
REGION=PRIVATE

the entire private key is one argument/parameter but the same key is assign to many parameters , please help me on the same . How to send the entire private key as one argument.

**Comment by jhoblitt** [comment]
This is not the correct place to ask for support on the usage of pipeline.  This would be better directed to IRC or the users mailing list. https://jenkins.io/mailing-lists/
